// ── 2026 NFL Draft Prospects ── Updated March 1, 2026 (Post-Combine) ──
// Sources: Tankathon, Drafttek, ESPN (Kiper/Yates/Reid), CBS Sports (Renner), PFF, Bleacher Report
// Note: Dante Moore returned to Oregon — NOT in 2026 draft class

export const ALL_PROSPECTS = [
  { name: "Fernando Mendoza", position: "QB", school: "Indiana" },
  { name: "Arvell Reese", position: "LB", school: "Ohio State" },
  { name: "Caleb Downs", position: "S", school: "Ohio State" },
  { name: "Rueben Bain Jr.", position: "EDGE", school: "Miami" },
  { name: "Sonny Styles", position: "LB", school: "Ohio State" },
  { name: "Francis Mauigoa", position: "OT", school: "Miami" },
  { name: "Spencer Fano", position: "OT", school: "Utah" },
  { name: "David Bailey", position: "EDGE", school: "Texas Tech" },
  { name: "Jeremiyah Love", position: "RB", school: "Notre Dame" },
  { name: "Carnell Tate", position: "WR", school: "Ohio State" },
  { name: "Makai Lemon", position: "WR", school: "USC" },
  { name: "Mansoor Delane", position: "CB", school: "LSU" },
  { name: "Jermod McCoy", position: "CB", school: "Tennessee" },
  { name: "Keldric Faulk", position: "EDGE", school: "Auburn" },
  { name: "Kenyon Sadiq", position: "TE", school: "Oregon" },
  { name: "Jordyn Tyson", position: "WR", school: "Arizona State" },
  { name: "Vega Ioane", position: "IOL", school: "Penn State" },
  { name: "Peter Woods", position: "DT", school: "Clemson" },
  { name: "Denzel Boston", position: "WR", school: "Washington" },
  { name: "T.J. Parker", position: "EDGE", school: "Clemson" },
  { name: "Kadyn Proctor", position: "OT", school: "Alabama" },
  { name: "Caleb Lomu", position: "OT", school: "Utah" },
  { name: "Dillon Thieneman", position: "S", school: "Oregon" },
  { name: "Avieon Terrell", position: "CB", school: "Clemson" },
  { name: "Cashius Howell", position: "EDGE", school: "Texas A&M" },
  { name: "Akheem Mesidor", position: "EDGE", school: "Miami" },
  { name: "Monroe Freeling", position: "OT", school: "Georgia" },
  { name: "Ty Simpson", position: "QB", school: "Alabama" },
  { name: "KC Concepcion", position: "WR", school: "Texas A&M" },
  { name: "Colton Hood", position: "CB", school: "Tennessee" },
  { name: "Anthony Hill Jr.", position: "LB", school: "Texas" },
  { name: "Christen Miller", position: "DT", school: "Georgia" },
  { name: "Caleb Banks", position: "DT", school: "Florida" },
  { name: "Kayden McDonald", position: "DT", school: "Ohio State" },
  { name: "Eli Stowers", position: "TE", school: "Vanderbilt" },
  { name: "C.J. Allen", position: "LB", school: "Georgia" },
  { name: "Brandon Cisse", position: "CB", school: "South Carolina" },
  { name: "D'Angelo Ponds", position: "CB", school: "Indiana" },
  { name: "Emmanuel McNeil-Warren", position: "S", school: "Toledo" },
  { name: "Lee Hunter", position: "DT", school: "Texas Tech" },
  { name: "Max Iheanachor", position: "OT", school: "Arizona State" },
  { name: "Romello Height", position: "EDGE", school: "Texas Tech" },
  { name: "Gabe Jacas", position: "EDGE", school: "Illinois" },
  { name: "Zachariah Branch", position: "WR", school: "Georgia" },
  { name: "Chris Bell", position: "WR", school: "Louisville" },
  { name: "Blake Miller", position: "OT", school: "Clemson" },
  { name: "Joshua Josephs", position: "EDGE", school: "Tennessee" },
  { name: "R Mason Thomas", position: "EDGE", school: "Oklahoma" },
  { name: "Dani Dennis-Sutton", position: "EDGE", school: "Penn State" },
  { name: "Emmanuel Pregnon", position: "IOL", school: "Oregon" },
  { name: "Chris Johnson", position: "CB", school: "San Diego State" },
  { name: "Keith Abney II", position: "CB", school: "Arizona State" },
  { name: "Keionte Scott", position: "S", school: "Miami" },
  { name: "Anthony Lucas", position: "EDGE", school: "USC" },
  { name: "Kyle Louis", position: "LB", school: "Pittsburgh" },
  { name: "Jadarian Price", position: "RB", school: "Notre Dame" },
  { name: "Jonah Coleman", position: "RB", school: "Washington" },
  { name: "Garrett Nussmeier", position: "QB", school: "LSU" },
  { name: "Carson Beck", position: "QB", school: "Miami" },
  { name: "Taylen Green", position: "QB", school: "Arkansas" },
];

// Draft order: 1-LV, 2-NYJ, 3-ARI, 4-TEN, 5-NYG, 6-CLE, 7-WSH, 8-NO, 9-KC, 10-CIN,
// 11-MIA, 12-DAL, 13-LAR(fromATL), 14-BAL, 15-TB, 16-NYJ(fromIND), 17-DET, 18-MIN,
// 19-CAR, 20-DAL(fromGB), 21-PIT, 22-LAC, 23-PHI, 24-CLE(fromJAX), 25-CHI, 26-BUF,
// 27-SF, 28-HOU, 29-LAR, 30-DEN, 31-NE, 32-SEA
export const PICK_SUGGESTIONS = {
  "1": [{ name: "Fernando Mendoza", position: "QB", school: "Indiana" }, { name: "Ty Simpson", position: "QB", school: "Alabama" }, { name: "Caleb Downs", position: "S", school: "Ohio State" }],
  "2": [{ name: "Rueben Bain Jr.", position: "EDGE", school: "Miami" }, { name: "Caleb Downs", position: "S", school: "Ohio State" }, { name: "Arvell Reese", position: "LB", school: "Ohio State" }],
  "3": [{ name: "Francis Mauigoa", position: "OT", school: "Miami" }, { name: "Caleb Downs", position: "S", school: "Ohio State" }, { name: "Ty Simpson", position: "QB", school: "Alabama" }],
  "4": [{ name: "Arvell Reese", position: "LB", school: "Ohio State" }, { name: "Ty Simpson", position: "QB", school: "Alabama" }, { name: "David Bailey", position: "EDGE", school: "Texas Tech" }],
  "5": [{ name: "Caleb Downs", position: "S", school: "Ohio State" }, { name: "Spencer Fano", position: "OT", school: "Utah" }, { name: "Francis Mauigoa", position: "OT", school: "Miami" }],
  "6": [{ name: "Spencer Fano", position: "OT", school: "Utah" }, { name: "Sonny Styles", position: "LB", school: "Ohio State" }, { name: "Carnell Tate", position: "WR", school: "Ohio State" }],
  "7": [{ name: "David Bailey", position: "EDGE", school: "Texas Tech" }, { name: "Rueben Bain Jr.", position: "EDGE", school: "Miami" }, { name: "Sonny Styles", position: "LB", school: "Ohio State" }],
  "8": [{ name: "Sonny Styles", position: "LB", school: "Ohio State" }, { name: "Arvell Reese", position: "LB", school: "Ohio State" }, { name: "Jeremiyah Love", position: "RB", school: "Notre Dame" }],
  "9": [{ name: "Jeremiyah Love", position: "RB", school: "Notre Dame" }, { name: "Keldric Faulk", position: "EDGE", school: "Auburn" }, { name: "Carnell Tate", position: "WR", school: "Ohio State" }],
  "10": [{ name: "Mansoor Delane", position: "CB", school: "LSU" }, { name: "Makai Lemon", position: "WR", school: "USC" }, { name: "Carnell Tate", position: "WR", school: "Ohio State" }],
  "11": [{ name: "Ty Simpson", position: "QB", school: "Alabama" }, { name: "Makai Lemon", position: "WR", school: "USC" }, { name: "Kenyon Sadiq", position: "TE", school: "Oregon" }],
  "12": [{ name: "Jermod McCoy", position: "CB", school: "Tennessee" }, { name: "Mansoor Delane", position: "CB", school: "LSU" }, { name: "Carnell Tate", position: "WR", school: "Ohio State" }],
  "13": [{ name: "Jermod McCoy", position: "CB", school: "Tennessee" }, { name: "Mansoor Delane", position: "CB", school: "LSU" }, { name: "Colton Hood", position: "CB", school: "Tennessee" }],
  "14": [{ name: "Keldric Faulk", position: "EDGE", school: "Auburn" }, { name: "Cashius Howell", position: "EDGE", school: "Texas A&M" }, { name: "Peter Woods", position: "DT", school: "Clemson" }],
  "15": [{ name: "Makai Lemon", position: "WR", school: "USC" }, { name: "Jordyn Tyson", position: "WR", school: "Arizona State" }, { name: "Peter Woods", position: "DT", school: "Clemson" }],
  "16": [{ name: "T.J. Parker", position: "EDGE", school: "Clemson" }, { name: "Kenyon Sadiq", position: "TE", school: "Oregon" }, { name: "Jordyn Tyson", position: "WR", school: "Arizona State" }],
  "17": [{ name: "Peter Woods", position: "DT", school: "Clemson" }, { name: "Denzel Boston", position: "WR", school: "Washington" }, { name: "Vega Ioane", position: "IOL", school: "Penn State" }],
  "18": [{ name: "Kenyon Sadiq", position: "TE", school: "Oregon" }, { name: "Carnell Tate", position: "WR", school: "Ohio State" }, { name: "Jordyn Tyson", position: "WR", school: "Arizona State" }],
  "19": [{ name: "Avieon Terrell", position: "CB", school: "Clemson" }, { name: "Cashius Howell", position: "EDGE", school: "Texas A&M" }, { name: "Dillon Thieneman", position: "S", school: "Oregon" }],
  "20": [{ name: "Caleb Lomu", position: "OT", school: "Utah" }, { name: "Kadyn Proctor", position: "OT", school: "Alabama" }, { name: "Vega Ioane", position: "IOL", school: "Penn State" }],
  "21": [{ name: "Ty Simpson", position: "QB", school: "Alabama" }, { name: "Kadyn Proctor", position: "OT", school: "Alabama" }, { name: "T.J. Parker", position: "EDGE", school: "Clemson" }],
  "22": [{ name: "Denzel Boston", position: "WR", school: "Washington" }, { name: "Dillon Thieneman", position: "S", school: "Oregon" }, { name: "Caleb Lomu", position: "OT", school: "Utah" }],
  "23": [{ name: "Akheem Mesidor", position: "EDGE", school: "Miami" }, { name: "Anthony Hill Jr.", position: "LB", school: "Texas" }, { name: "Christen Miller", position: "DT", school: "Georgia" }],
  "24": [{ name: "Christen Miller", position: "DT", school: "Georgia" }, { name: "KC Concepcion", position: "WR", school: "Texas A&M" }, { name: "Caleb Banks", position: "DT", school: "Florida" }],
  "25": [{ name: "KC Concepcion", position: "WR", school: "Texas A&M" }, { name: "Denzel Boston", position: "WR", school: "Washington" }, { name: "Dillon Thieneman", position: "S", school: "Oregon" }],
  "26": [{ name: "Monroe Freeling", position: "OT", school: "Georgia" }, { name: "Caleb Lomu", position: "OT", school: "Utah" }, { name: "Eli Stowers", position: "TE", school: "Vanderbilt" }],
  "27": [{ name: "Kadyn Proctor", position: "OT", school: "Alabama" }, { name: "Anthony Hill Jr.", position: "LB", school: "Texas" }, { name: "Colton Hood", position: "CB", school: "Tennessee" }],
  "28": [{ name: "Kayden McDonald", position: "DT", school: "Ohio State" }, { name: "Vega Ioane", position: "IOL", school: "Penn State" }, { name: "C.J. Allen", position: "LB", school: "Georgia" }],
  "29": [{ name: "Colton Hood", position: "CB", school: "Tennessee" }, { name: "Brandon Cisse", position: "CB", school: "South Carolina" }, { name: "Avieon Terrell", position: "CB", school: "Clemson" }],
  "30": [{ name: "Eli Stowers", position: "TE", school: "Vanderbilt" }, { name: "Emmanuel Pregnon", position: "IOL", school: "Oregon" }, { name: "Dillon Thieneman", position: "S", school: "Oregon" }],
  "31": [{ name: "Gabe Jacas", position: "EDGE", school: "Illinois" }, { name: "Blake Miller", position: "OT", school: "Clemson" }, { name: "Chris Bell", position: "WR", school: "Louisville" }],
  "32": [{ name: "Avieon Terrell", position: "CB", school: "Clemson" }, { name: "Colton Hood", position: "CB", school: "Tennessee" }, { name: "D'Angelo Ponds", position: "CB", school: "Indiana" }],
};
