// NBA Career Path data — curated notable retired players
// Teams listed in CHRONOLOGICAL order (career progression)
// Last updated: February 2026

export const NBA_CAREER_PATHS = [
  // ── All-time greats ──
  {name:"Michael Jordan",teams:["Chicago Bulls","Washington Wizards"]},
  {name:"Shaquille O'Neal",teams:["Orlando Magic","Los Angeles Lakers","Miami Heat","Phoenix Suns","Cleveland Cavaliers","Boston Celtics"]},
  {name:"Kareem Abdul-Jabbar",teams:["Milwaukee Bucks","Los Angeles Lakers"]},
  {name:"Wilt Chamberlain",teams:["Philadelphia Warriors","San Francisco Warriors","Philadelphia 76ers","Los Angeles Lakers"]},
  {name:"Hakeem Olajuwon",teams:["Houston Rockets","Toronto Raptors"]},
  {name:"Karl Malone",teams:["Utah Jazz","Los Angeles Lakers"]},
  {name:"Charles Barkley",teams:["Philadelphia 76ers","Phoenix Suns","Houston Rockets"]},
  {name:"Moses Malone",teams:["Houston Rockets","Philadelphia 76ers","Washington Wizards","Atlanta Hawks","Milwaukee Bucks","San Antonio Spurs"]},
  {name:"Oscar Robertson",teams:["Cincinnati Royals","Milwaukee Bucks"]},
  {name:"Pete Maravich",teams:["Atlanta Hawks","New Orleans Jazz","Boston Celtics"]},
  {name:"Patrick Ewing",teams:["New York Knicks","Seattle SuperSonics","Orlando Magic"]},

  // ── Modern legends ──
  {name:"Kevin Garnett",teams:["Minnesota Timberwolves","Boston Celtics","Brooklyn Nets","Minnesota Timberwolves"]},
  {name:"Dwyane Wade",teams:["Miami Heat","Chicago Bulls","Cleveland Cavaliers","Miami Heat"]},
  {name:"Allen Iverson",teams:["Philadelphia 76ers","Denver Nuggets","Detroit Pistons","Memphis Grizzlies","Philadelphia 76ers"]},
  {name:"Steve Nash",teams:["Phoenix Suns","Dallas Mavericks","Phoenix Suns","Los Angeles Lakers"]},
  {name:"Ray Allen",teams:["Milwaukee Bucks","Seattle SuperSonics","Boston Celtics","Miami Heat"]},
  {name:"Paul Pierce",teams:["Boston Celtics","Brooklyn Nets","Washington Wizards","Los Angeles Clippers"]},
  {name:"Tony Parker",teams:["San Antonio Spurs","Charlotte Hornets"]},
  {name:"Vince Carter",teams:["Toronto Raptors","Brooklyn Nets","Orlando Magic","Phoenix Suns","Dallas Mavericks","Memphis Grizzlies","Sacramento Kings","Atlanta Hawks"]},
  {name:"Tracy McGrady",teams:["Toronto Raptors","Orlando Magic","Houston Rockets","New York Knicks","Detroit Pistons","Atlanta Hawks","San Antonio Spurs"]},
  {name:"Carmelo Anthony",teams:["Denver Nuggets","New York Knicks","Oklahoma City Thunder","Houston Rockets","Portland Trail Blazers","Los Angeles Lakers"]},
  {name:"Chris Bosh",teams:["Toronto Raptors","Miami Heat"]},
  {name:"Pau Gasol",teams:["Memphis Grizzlies","Los Angeles Lakers","Chicago Bulls","San Antonio Spurs","Milwaukee Bucks"]},
  {name:"Rajon Rondo",teams:["Boston Celtics","Dallas Mavericks","Sacramento Kings","Chicago Bulls","New Orleans Pelicans","Los Angeles Lakers","Atlanta Hawks","Los Angeles Clippers","Cleveland Cavaliers"]},

  // ── HOF-era greats ──
  {name:"Jason Kidd",teams:["Dallas Mavericks","Phoenix Suns","New Jersey Nets","Dallas Mavericks","New York Knicks"]},
  {name:"Gary Payton",teams:["Seattle SuperSonics","Milwaukee Bucks","Los Angeles Lakers","Boston Celtics","Miami Heat"]},
  {name:"Scottie Pippen",teams:["Chicago Bulls","Houston Rockets","Portland Trail Blazers","Chicago Bulls"]},
  {name:"Dennis Rodman",teams:["Detroit Pistons","San Antonio Spurs","Chicago Bulls","Los Angeles Lakers","Dallas Mavericks"]},
  {name:"Clyde Drexler",teams:["Portland Trail Blazers","Houston Rockets"]},
  {name:"Dominique Wilkins",teams:["Atlanta Hawks","Los Angeles Clippers","Boston Celtics","San Antonio Spurs","Orlando Magic"]},
  {name:"Robert Parish",teams:["Golden State Warriors","Boston Celtics","Charlotte Hornets","Chicago Bulls"]},

  // ── 2000s–2010s stars ──
  {name:"Chauncey Billups",teams:["Boston Celtics","Toronto Raptors","Denver Nuggets","Minnesota Timberwolves","Detroit Pistons","Denver Nuggets","New York Knicks","Los Angeles Clippers"]},
  {name:"Ben Wallace",teams:["Washington Wizards","Orlando Magic","Detroit Pistons","Chicago Bulls","Cleveland Cavaliers","Detroit Pistons"]},
  {name:"Rasheed Wallace",teams:["Washington Wizards","Portland Trail Blazers","Atlanta Hawks","Detroit Pistons","Boston Celtics","New York Knicks"]},
  {name:"Gilbert Arenas",teams:["Golden State Warriors","Washington Wizards","Orlando Magic","Memphis Grizzlies"]},
  {name:"Baron Davis",teams:["Charlotte Hornets","Golden State Warriors","Los Angeles Clippers","Cleveland Cavaliers","New York Knicks"]},
  {name:"Stephon Marbury",teams:["Minnesota Timberwolves","New Jersey Nets","Phoenix Suns","New York Knicks","Boston Celtics"]},
  {name:"Steve Francis",teams:["Houston Rockets","Orlando Magic","New York Knicks","Houston Rockets"]},
  {name:"Jamal Crawford",teams:["Chicago Bulls","New York Knicks","Golden State Warriors","Atlanta Hawks","Portland Trail Blazers","Los Angeles Clippers","Minnesota Timberwolves","Phoenix Suns","Brooklyn Nets"]},
  {name:"Metta World Peace",teams:["Chicago Bulls","Indiana Pacers","Sacramento Kings","Houston Rockets","Los Angeles Lakers","New York Knicks","Los Angeles Lakers"]},
  {name:"Lamar Odom",teams:["Los Angeles Clippers","Miami Heat","Los Angeles Lakers","Dallas Mavericks","Los Angeles Clippers"]},
  {name:"Caron Butler",teams:["Miami Heat","Los Angeles Lakers","Washington Wizards","Dallas Mavericks","Los Angeles Clippers","Milwaukee Bucks","Oklahoma City Thunder","Detroit Pistons","Sacramento Kings"]},
  {name:"Antawn Jamison",teams:["Golden State Warriors","Dallas Mavericks","Washington Wizards","Cleveland Cavaliers","Los Angeles Lakers","Los Angeles Clippers"]},
  {name:"Elton Brand",teams:["Chicago Bulls","Los Angeles Clippers","Philadelphia 76ers","Dallas Mavericks","Atlanta Hawks"]},
  {name:"Jermaine O'Neal",teams:["Portland Trail Blazers","Indiana Pacers","Toronto Raptors","Miami Heat","Boston Celtics","Phoenix Suns","Golden State Warriors"]},
  {name:"Shawn Marion",teams:["Phoenix Suns","Miami Heat","Toronto Raptors","Dallas Mavericks","Cleveland Cavaliers"]},
  {name:"Mike Bibby",teams:["Vancouver Grizzlies","Sacramento Kings","Atlanta Hawks","Washington Wizards","Miami Heat","New York Knicks"]},
  {name:"Peja Stojakovic",teams:["Sacramento Kings","Indiana Pacers","New Orleans Hornets","Toronto Raptors","Dallas Mavericks"]},
  {name:"Mike Miller",teams:["Orlando Magic","Memphis Grizzlies","Minnesota Timberwolves","Washington Wizards","Miami Heat","Memphis Grizzlies","Cleveland Cavaliers","Denver Nuggets"]},
  {name:"Rashard Lewis",teams:["Seattle SuperSonics","Orlando Magic","Washington Wizards","Miami Heat"]},
  {name:"Richard Jefferson",teams:["New Jersey Nets","Milwaukee Bucks","San Antonio Spurs","Golden State Warriors","Utah Jazz","Dallas Mavericks","Cleveland Cavaliers","Denver Nuggets"]},
  {name:"Shane Battier",teams:["Memphis Grizzlies","Houston Rockets","Memphis Grizzlies","Miami Heat"]},
  {name:"Boris Diaw",teams:["Atlanta Hawks","Phoenix Suns","Charlotte Bobcats","San Antonio Spurs","Utah Jazz"]},
  {name:"Robert Horry",teams:["Houston Rockets","Phoenix Suns","Los Angeles Lakers","San Antonio Spurs"]},
  {name:"Derek Fisher",teams:["Los Angeles Lakers","Golden State Warriors","Utah Jazz","Los Angeles Lakers","Oklahoma City Thunder"]},
  {name:"Horace Grant",teams:["Chicago Bulls","Orlando Magic","Seattle SuperSonics","Los Angeles Lakers","Orlando Magic"]},

  // ── Recent retirees ──
  {name:"LaMarcus Aldridge",teams:["Portland Trail Blazers","San Antonio Spurs","Brooklyn Nets"]},
  {name:"Marc Gasol",teams:["Memphis Grizzlies","Toronto Raptors","Los Angeles Lakers"]},
  {name:"Tyson Chandler",teams:["Los Angeles Clippers","Chicago Bulls","New Orleans Hornets","Dallas Mavericks","New York Knicks","Dallas Mavericks","Phoenix Suns","Los Angeles Lakers","Houston Rockets"]},
  {name:"Nene",teams:["Denver Nuggets","Washington Wizards","Houston Rockets"]},
  {name:"Joakim Noah",teams:["Chicago Bulls","New York Knicks","Memphis Grizzlies","Los Angeles Clippers"]},
  {name:"Andrew Bogut",teams:["Milwaukee Bucks","Golden State Warriors","Dallas Mavericks","Cleveland Cavaliers","Los Angeles Lakers"]},
  {name:"David West",teams:["New Orleans Hornets","Indiana Pacers","San Antonio Spurs","Golden State Warriors"]},
  {name:"Zach Randolph",teams:["Portland Trail Blazers","New York Knicks","Los Angeles Clippers","Memphis Grizzlies","Sacramento Kings"]},
  {name:"Joe Johnson",teams:["Boston Celtics","Phoenix Suns","Atlanta Hawks","Brooklyn Nets","Miami Heat","Utah Jazz","Houston Rockets","Detroit Pistons"]},
  {name:"Amar'e Stoudemire",teams:["Phoenix Suns","New York Knicks","Dallas Mavericks","Miami Heat"]},
  {name:"Blake Griffin",teams:["Los Angeles Clippers","Detroit Pistons","Brooklyn Nets","Boston Celtics"]},
  {name:"DeAndre Jordan",teams:["Los Angeles Clippers","Dallas Mavericks","New York Knicks","Brooklyn Nets","Los Angeles Lakers","Philadelphia 76ers","Denver Nuggets"]},
  {name:"Derrick Rose",teams:["Chicago Bulls","New York Knicks","Cleveland Cavaliers","Minnesota Timberwolves","Detroit Pistons","New York Knicks","Memphis Grizzlies"]},

  // ── Notable journeymen & multi-team stars ──
  {name:"Matt Barnes",teams:["Cleveland Cavaliers","Sacramento Kings","Los Angeles Clippers","New York Knicks","Philadelphia 76ers","Golden State Warriors","Phoenix Suns","Orlando Magic","Los Angeles Lakers","Los Angeles Clippers","Memphis Grizzlies","Sacramento Kings","Golden State Warriors"]},
  {name:"Stephen Jackson",teams:["New Jersey Nets","San Antonio Spurs","Atlanta Hawks","Indiana Pacers","Golden State Warriors","Charlotte Bobcats","Milwaukee Bucks","San Antonio Spurs","Los Angeles Clippers"]},
  {name:"Corey Brewer",teams:["Minnesota Timberwolves","Dallas Mavericks","Denver Nuggets","Minnesota Timberwolves","Houston Rockets","Los Angeles Lakers","Oklahoma City Thunder","Philadelphia 76ers","Sacramento Kings"]},
  {name:"Ricky Davis",teams:["Charlotte Hornets","Cleveland Cavaliers","Boston Celtics","Minnesota Timberwolves","Miami Heat","Los Angeles Clippers"]},
  {name:"Channing Frye",teams:["New York Knicks","Portland Trail Blazers","Phoenix Suns","Orlando Magic","Cleveland Cavaliers","Los Angeles Lakers","Cleveland Cavaliers"]},
  {name:"David Lee",teams:["New York Knicks","Golden State Warriors","Boston Celtics","Dallas Mavericks","San Antonio Spurs"]},
  {name:"Greg Monroe",teams:["Detroit Pistons","Milwaukee Bucks","Phoenix Suns","Boston Celtics","Toronto Raptors","Philadelphia 76ers","Minnesota Timberwolves"]},
  {name:"Ersan Ilyasova",teams:["Milwaukee Bucks","Detroit Pistons","Orlando Magic","Oklahoma City Thunder","Philadelphia 76ers","Atlanta Hawks","Milwaukee Bucks"]},

  // ── '90s icons ──
  {name:"Alonzo Mourning",teams:["Charlotte Hornets","Miami Heat","New Jersey Nets","Miami Heat"]},
  {name:"Dikembe Mutombo",teams:["Denver Nuggets","Atlanta Hawks","Philadelphia 76ers","New Jersey Nets","New York Knicks","Houston Rockets"]},
  {name:"Tim Hardaway",teams:["Golden State Warriors","Miami Heat","Dallas Mavericks","Denver Nuggets","Indiana Pacers"]},
  {name:"Mitch Richmond",teams:["Golden State Warriors","Sacramento Kings","Washington Wizards","Los Angeles Lakers"]},
  {name:"Detlef Schrempf",teams:["Dallas Mavericks","Indiana Pacers","Seattle SuperSonics","Portland Trail Blazers"]},
  {name:"Dan Majerle",teams:["Phoenix Suns","Cleveland Cavaliers","Miami Heat"]},
  {name:"Cliff Robinson",teams:["Portland Trail Blazers","Phoenix Suns","Detroit Pistons","Golden State Warriors","New Jersey Nets"]},
  {name:"Sam Cassell",teams:["Houston Rockets","Phoenix Suns","Dallas Mavericks","New Jersey Nets","Milwaukee Bucks","Minnesota Timberwolves","Los Angeles Clippers","Boston Celtics","Sacramento Kings"]},
  {name:"Latrell Sprewell",teams:["Golden State Warriors","New York Knicks","Minnesota Timberwolves"]},
  {name:"Vin Baker",teams:["Milwaukee Bucks","Seattle SuperSonics","Boston Celtics","New York Knicks","Houston Rockets","Los Angeles Clippers","Minnesota Timberwolves"]},
  {name:"Shawn Kemp",teams:["Seattle SuperSonics","Cleveland Cavaliers","Portland Trail Blazers","Orlando Magic"]},
  {name:"Grant Hill",teams:["Detroit Pistons","Orlando Magic","Phoenix Suns","Los Angeles Clippers"]},
  {name:"Jason Williams",teams:["Sacramento Kings","Memphis Grizzlies","Miami Heat","Orlando Magic"]},
  {name:"Larry Johnson",teams:["Charlotte Hornets","New York Knicks"]},
  {name:"Allan Houston",teams:["Detroit Pistons","New York Knicks"]},

  // ── More notable multi-team players ──
  {name:"Deron Williams",teams:["Utah Jazz","Brooklyn Nets","Dallas Mavericks","Cleveland Cavaliers"]},
  {name:"Marcin Gortat",teams:["Orlando Magic","Phoenix Suns","Washington Wizards","Los Angeles Clippers"]},
  {name:"JaVale McGee",teams:["Washington Wizards","Denver Nuggets","Dallas Mavericks","Philadelphia 76ers","Golden State Warriors","Los Angeles Lakers","Cleveland Cavaliers","Phoenix Suns","Sacramento Kings"]},
  {name:"Darren Collison",teams:["New Orleans Hornets","Indiana Pacers","Dallas Mavericks","Sacramento Kings","Indiana Pacers"]},
  {name:"George Hill",teams:["San Antonio Spurs","Indiana Pacers","Utah Jazz","Sacramento Kings","Cleveland Cavaliers","Milwaukee Bucks","Oklahoma City Thunder","Philadelphia 76ers","Indiana Pacers"]},
  {name:"D.J. Augustin",teams:["Charlotte Bobcats","Indiana Pacers","Toronto Raptors","Chicago Bulls","Oklahoma City Thunder","Denver Nuggets","Orlando Magic","Milwaukee Bucks","Houston Rockets","Los Angeles Lakers","Philadelphia 76ers"]},
  {name:"Raymond Felton",teams:["Charlotte Bobcats","New York Knicks","Denver Nuggets","Portland Trail Blazers","New York Knicks","Dallas Mavericks","Los Angeles Clippers","Oklahoma City Thunder"]},
  {name:"Jameer Nelson",teams:["Orlando Magic","Denver Nuggets","Dallas Mavericks","Boston Celtics","New Orleans Pelicans","Detroit Pistons","Washington Wizards"]},
  {name:"Jose Calderon",teams:["Toronto Raptors","Detroit Pistons","Dallas Mavericks","New York Knicks","Los Angeles Lakers","Atlanta Hawks","Cleveland Cavaliers"]},
  {name:"Mario Chalmers",teams:["Miami Heat","Memphis Grizzlies"]},
  {name:"Jason Terry",teams:["Atlanta Hawks","Dallas Mavericks","Boston Celtics","Brooklyn Nets","Houston Rockets","Milwaukee Bucks"]},
  {name:"Evan Turner",teams:["Philadelphia 76ers","Indiana Pacers","Boston Celtics","Portland Trail Blazers","Atlanta Hawks","Minnesota Timberwolves"]},
  {name:"Chandler Parsons",teams:["Houston Rockets","Dallas Mavericks","Memphis Grizzlies","Atlanta Hawks"]},
  {name:"Wilson Chandler",teams:["New York Knicks","Denver Nuggets","Philadelphia 76ers","Los Angeles Clippers","Brooklyn Nets","Indiana Pacers"]},
  {name:"Danilo Gallinari",teams:["New York Knicks","Denver Nuggets","Los Angeles Clippers","Oklahoma City Thunder","Atlanta Hawks","Boston Celtics","Washington Wizards","Milwaukee Bucks","Detroit Pistons"]},
  {name:"Luol Deng",teams:["Chicago Bulls","Cleveland Cavaliers","Miami Heat","Los Angeles Lakers","Minnesota Timberwolves"]},
  {name:"Carlos Boozer",teams:["Cleveland Cavaliers","Utah Jazz","Chicago Bulls","Los Angeles Lakers"]},
  {name:"Chris Kaman",teams:["Los Angeles Clippers","New Orleans Hornets","Dallas Mavericks","Los Angeles Lakers","Portland Trail Blazers","Detroit Pistons"]},
  {name:"Andrea Bargnani",teams:["Toronto Raptors","New York Knicks","Brooklyn Nets"]},
  {name:"Kenyon Martin",teams:["New Jersey Nets","Denver Nuggets","Los Angeles Clippers","New York Knicks","Milwaukee Bucks"]},
  {name:"Antoine Walker",teams:["Boston Celtics","Dallas Mavericks","Atlanta Hawks","Boston Celtics","Miami Heat","Minnesota Timberwolves"]},
  {name:"Jerry Stackhouse",teams:["Philadelphia 76ers","Detroit Pistons","Washington Wizards","Dallas Mavericks","Milwaukee Bucks","Miami Heat","Atlanta Hawks","Brooklyn Nets"]},
  {name:"Shareef Abdur-Rahim",teams:["Vancouver Grizzlies","Atlanta Hawks","Portland Trail Blazers","Sacramento Kings"]},
  {name:"Theo Ratliff",teams:["Detroit Pistons","Philadelphia 76ers","Atlanta Hawks","Portland Trail Blazers","Boston Celtics","Minnesota Timberwolves","San Antonio Spurs","Philadelphia 76ers","Charlotte Bobcats","Los Angeles Lakers"]},
  {name:"Erick Dampier",teams:["Indiana Pacers","Golden State Warriors","Dallas Mavericks","Miami Heat","Atlanta Hawks"]},
  {name:"Brendan Haywood",teams:["Washington Wizards","Dallas Mavericks","Charlotte Bobcats","Cleveland Cavaliers"]},
  {name:"Derrick Coleman",teams:["New Jersey Nets","Philadelphia 76ers","Charlotte Hornets","Philadelphia 76ers","Detroit Pistons"]},
  {name:"Nick Van Exel",teams:["Los Angeles Lakers","Denver Nuggets","Dallas Mavericks","Golden State Warriors","Portland Trail Blazers","San Antonio Spurs"]},
  {name:"Eddie Jones",teams:["Los Angeles Lakers","Charlotte Hornets","Miami Heat","Memphis Grizzlies","Dallas Mavericks"]},
  {name:"John Starks",teams:["Golden State Warriors","New York Knicks","Golden State Warriors","Chicago Bulls","Utah Jazz"]},
  {name:"Mookie Blaylock",teams:["New Jersey Nets","Atlanta Hawks","Golden State Warriors"]},
  {name:"Rod Strickland",teams:["New York Knicks","San Antonio Spurs","Portland Trail Blazers","Washington Wizards","Miami Heat","Minnesota Timberwolves","Dallas Mavericks","Orlando Magic","Houston Rockets","Toronto Raptors"]},
  {name:"Mark Jackson",teams:["New York Knicks","Los Angeles Clippers","Indiana Pacers","Denver Nuggets","Indiana Pacers","Toronto Raptors","Utah Jazz","New York Knicks","Houston Rockets"]},
  {name:"Muggsy Bogues",teams:["Washington Wizards","Charlotte Hornets","Golden State Warriors","Toronto Raptors","Dallas Mavericks"]},
  {name:"Terry Porter",teams:["Portland Trail Blazers","Minnesota Timberwolves","Miami Heat","San Antonio Spurs"]},
  {name:"Vernon Maxwell",teams:["San Antonio Spurs","Houston Rockets","Philadelphia 76ers","Orlando Magic","San Antonio Spurs","Sacramento Kings","Seattle SuperSonics"]},
  {name:"Mario Elie",teams:["Philadelphia 76ers","Golden State Warriors","Portland Trail Blazers","Houston Rockets","San Antonio Spurs","Phoenix Suns","Los Angeles Lakers"]},

  // ── Additional fun career paths ──
  {name:"Andre Iguodala",teams:["Philadelphia 76ers","Denver Nuggets","Golden State Warriors","Miami Heat","Golden State Warriors"]},
  {name:"Kyle Korver",teams:["Philadelphia 76ers","Utah Jazz","Chicago Bulls","Atlanta Hawks","Cleveland Cavaliers","Utah Jazz","Milwaukee Bucks"]},
  {name:"Danny Green",teams:["Cleveland Cavaliers","San Antonio Spurs","Toronto Raptors","Los Angeles Lakers","Philadelphia 76ers","Memphis Grizzlies","Cleveland Cavaliers","Philadelphia 76ers"]},
  {name:"Lou Williams",teams:["Philadelphia 76ers","Atlanta Hawks","Toronto Raptors","Los Angeles Lakers","Houston Rockets","Los Angeles Clippers","Atlanta Hawks"]},
  {name:"Nikola Mirotic",teams:["Chicago Bulls","New Orleans Pelicans","Milwaukee Bucks"]},
  {name:"Nemanja Bjelica",teams:["Minnesota Timberwolves","Sacramento Kings","Miami Heat","Golden State Warriors","Phoenix Suns"]},
  {name:"DeMarcus Cousins",teams:["Sacramento Kings","New Orleans Pelicans","Golden State Warriors","Houston Rockets","Los Angeles Clippers","Milwaukee Bucks","Denver Nuggets"]},
  {name:"Andre Drummond",teams:["Detroit Pistons","Cleveland Cavaliers","Los Angeles Lakers","Philadelphia 76ers","Brooklyn Nets","Chicago Bulls"]},
  {name:"Isaiah Thomas",teams:["Sacramento Kings","Phoenix Suns","Boston Celtics","Cleveland Cavaliers","Los Angeles Lakers","Denver Nuggets","Washington Wizards","Dallas Mavericks","Charlotte Hornets","Phoenix Suns"]},
  {name:"Nerlens Noel",teams:["Philadelphia 76ers","Dallas Mavericks","Oklahoma City Thunder","New York Knicks","Detroit Pistons"]},
  {name:"Hassan Whiteside",teams:["Sacramento Kings","Miami Heat","Portland Trail Blazers","Sacramento Kings","Utah Jazz"]},
  {name:"Tristan Thompson",teams:["Cleveland Cavaliers","Boston Celtics","Sacramento Kings","Indiana Pacers","Chicago Bulls","Cleveland Cavaliers"]},
  {name:"Robin Lopez",teams:["Phoenix Suns","New Orleans Hornets","Portland Trail Blazers","New York Knicks","Chicago Bulls","Milwaukee Bucks","Washington Wizards","Orlando Magic","Cleveland Cavaliers"]},
  {name:"Serge Ibaka",teams:["Oklahoma City Thunder","Orlando Magic","Toronto Raptors","Los Angeles Clippers","Milwaukee Bucks","Indiana Pacers"]},
  {name:"Jeff Green",teams:["Seattle SuperSonics","Oklahoma City Thunder","Boston Celtics","Memphis Grizzlies","Los Angeles Clippers","Orlando Magic","Cleveland Cavaliers","Washington Wizards","Houston Rockets","Brooklyn Nets","Denver Nuggets"]},
  {name:"Rudy Gay",teams:["Memphis Grizzlies","Toronto Raptors","Sacramento Kings","San Antonio Spurs","Utah Jazz"]},
  {name:"Thaddeus Young",teams:["Philadelphia 76ers","Minnesota Timberwolves","Brooklyn Nets","Indiana Pacers","Chicago Bulls","San Antonio Spurs","Toronto Raptors","Phoenix Suns"]},
  {name:"Garrett Temple",teams:["Houston Rockets","San Antonio Spurs","Sacramento Kings","Washington Wizards","Milwaukee Bucks","Memphis Grizzlies","Los Angeles Clippers","Brooklyn Nets","Chicago Bulls","New Orleans Pelicans","Toronto Raptors"]},
];
