// NBA Career Path Quiz - Player data
// Each player has teams in chronological order
// difficulty: 1 (easy - iconic journeys) to 5 (hard - obscure paths)

export const NBA_CAREER_PATHS = [
  // Easy - iconic journeys everyone knows
  {name:"LeBron James",teams:["Cleveland Cavaliers","Miami Heat","Cleveland Cavaliers","Los Angeles Lakers"],difficulty:1},
  {name:"Shaquille O'Neal",teams:["Orlando Magic","Los Angeles Lakers","Miami Heat","Phoenix Suns","Cleveland Cavaliers","Boston Celtics"],difficulty:1},
  {name:"Kevin Durant",teams:["Oklahoma City Thunder","Golden State Warriors","Brooklyn Nets","Phoenix Suns"],difficulty:1},
  {name:"James Harden",teams:["Oklahoma City Thunder","Houston Rockets","Brooklyn Nets","Philadelphia 76ers","Los Angeles Clippers"],difficulty:1},
  {name:"Carmelo Anthony",teams:["Denver Nuggets","New York Knicks","Oklahoma City Thunder","Houston Rockets","Portland Trail Blazers","Los Angeles Lakers"],difficulty:1},
  {name:"Chris Paul",teams:["New Orleans Pelicans","Los Angeles Clippers","Houston Rockets","Oklahoma City Thunder","Phoenix Suns","Golden State Warriors","San Antonio Spurs"],difficulty:1},
  {name:"Dwight Howard",teams:["Orlando Magic","Los Angeles Lakers","Houston Rockets","Atlanta Hawks","Charlotte Hornets","Washington Wizards","Philadelphia 76ers","Los Angeles Lakers"],difficulty:1},
  {name:"Kyrie Irving",teams:["Cleveland Cavaliers","Boston Celtics","Brooklyn Nets","Dallas Mavericks"],difficulty:1},
  {name:"Russell Westbrook",teams:["Oklahoma City Thunder","Houston Rockets","Washington Wizards","Los Angeles Lakers","Los Angeles Clippers","Denver Nuggets"],difficulty:1},
  {name:"Dwyane Wade",teams:["Miami Heat","Chicago Bulls","Cleveland Cavaliers","Miami Heat"],difficulty:1},
  {name:"Allen Iverson",teams:["Philadelphia 76ers","Denver Nuggets","Detroit Pistons","Memphis Grizzlies","Philadelphia 76ers"],difficulty:1},
  {name:"Kevin Garnett",teams:["Minnesota Timberwolves","Boston Celtics","Brooklyn Nets","Minnesota Timberwolves"],difficulty:1},
  {name:"Vince Carter",teams:["Toronto Raptors","New Jersey Nets","Orlando Magic","Phoenix Suns","Dallas Mavericks","Memphis Grizzlies","Sacramento Kings","Atlanta Hawks"],difficulty:1},
  {name:"Charles Barkley",teams:["Philadelphia 76ers","Phoenix Suns","Houston Rockets"],difficulty:1},
  {name:"Ray Allen",teams:["Milwaukee Bucks","Seattle SuperSonics","Boston Celtics","Miami Heat"],difficulty:2},
  {name:"Paul Pierce",teams:["Boston Celtics","Brooklyn Nets","Washington Wizards","Los Angeles Clippers"],difficulty:2},
  {name:"Damian Lillard",teams:["Portland Trail Blazers","Milwaukee Bucks"],difficulty:2},
  {name:"Jimmy Butler",teams:["Chicago Bulls","Minnesota Timberwolves","Philadelphia 76ers","Miami Heat"],difficulty:2},
  // Medium
  {name:"Steve Nash",teams:["Phoenix Suns","Dallas Mavericks","Phoenix Suns","Los Angeles Lakers"],difficulty:2},
  {name:"Jason Kidd",teams:["Dallas Mavericks","Phoenix Suns","New Jersey Nets","Dallas Mavericks","New York Knicks"],difficulty:2},
  {name:"Tracy McGrady",teams:["Toronto Raptors","Orlando Magic","Houston Rockets","New York Knicks","Detroit Pistons","Atlanta Hawks","San Antonio Spurs"],difficulty:2},
  {name:"Gary Payton",teams:["Seattle SuperSonics","Milwaukee Bucks","Los Angeles Lakers","Boston Celtics","Miami Heat"],difficulty:2},
  {name:"Scottie Pippen",teams:["Chicago Bulls","Houston Rockets","Portland Trail Blazers","Chicago Bulls"],difficulty:2},
  {name:"Blake Griffin",teams:["Los Angeles Clippers","Detroit Pistons","Brooklyn Nets","Boston Celtics"],difficulty:2},
  {name:"Rajon Rondo",teams:["Boston Celtics","Dallas Mavericks","Sacramento Kings","Chicago Bulls","New Orleans Pelicans","Los Angeles Lakers","Atlanta Hawks","Los Angeles Clippers","Cleveland Cavaliers"],difficulty:2},
  {name:"DeMar DeRozan",teams:["Toronto Raptors","San Antonio Spurs","Chicago Bulls","Sacramento Kings"],difficulty:2},
  {name:"Paul George",teams:["Indiana Pacers","Oklahoma City Thunder","Los Angeles Clippers","Philadelphia 76ers"],difficulty:2},
  {name:"Derrick Rose",teams:["Chicago Bulls","New York Knicks","Cleveland Cavaliers","Minnesota Timberwolves","Detroit Pistons","New York Knicks","Memphis Grizzlies"],difficulty:2},
  {name:"Kristaps Porzingis",teams:["New York Knicks","Dallas Mavericks","Washington Wizards","Boston Celtics"],difficulty:2},
  {name:"D'Angelo Russell",teams:["Los Angeles Lakers","Brooklyn Nets","Golden State Warriors","Minnesota Timberwolves"],difficulty:2},
  {name:"Kyle Lowry",teams:["Memphis Grizzlies","Houston Rockets","Toronto Raptors","Miami Heat","Philadelphia 76ers"],difficulty:2},
  {name:"DeMarcus Cousins",teams:["Sacramento Kings","New Orleans Pelicans","Golden State Warriors","Houston Rockets","Los Angeles Clippers","Milwaukee Bucks","Denver Nuggets"],difficulty:2},
  {name:"John Wall",teams:["Washington Wizards","Houston Rockets","Los Angeles Clippers"],difficulty:2},
  {name:"Victor Oladipo",teams:["Orlando Magic","Oklahoma City Thunder","Indiana Pacers","Houston Rockets","Miami Heat"],difficulty:3},
  // Harder
  {name:"Chauncey Billups",teams:["Boston Celtics","Toronto Raptors","Denver Nuggets","Minnesota Timberwolves","Detroit Pistons","Denver Nuggets","New York Knicks","Los Angeles Clippers"],difficulty:3},
  {name:"Jrue Holiday",teams:["Philadelphia 76ers","New Orleans Pelicans","Milwaukee Bucks","Boston Celtics"],difficulty:3},
  {name:"Tobias Harris",teams:["Milwaukee Bucks","Orlando Magic","Detroit Pistons","Los Angeles Clippers","Philadelphia 76ers"],difficulty:3},
  {name:"Julius Randle",teams:["Los Angeles Lakers","New Orleans Pelicans","New York Knicks","Minnesota Timberwolves"],difficulty:3},
  {name:"Andre Iguodala",teams:["Philadelphia 76ers","Denver Nuggets","Golden State Warriors","Miami Heat","Golden State Warriors"],difficulty:3},
  {name:"Serge Ibaka",teams:["Oklahoma City Thunder","Orlando Magic","Toronto Raptors","Los Angeles Clippers","Milwaukee Bucks"],difficulty:3},
  {name:"Danny Green",teams:["Cleveland Cavaliers","San Antonio Spurs","Toronto Raptors","Los Angeles Lakers","Philadelphia 76ers","Memphis Grizzlies"],difficulty:3},
  {name:"Metta World Peace",teams:["Chicago Bulls","Indiana Pacers","Sacramento Kings","Houston Rockets","Los Angeles Lakers","New York Knicks"],difficulty:3},
  {name:"Lamar Odom",teams:["Los Angeles Clippers","Miami Heat","Los Angeles Lakers","Dallas Mavericks"],difficulty:3},
  {name:"Pau Gasol",teams:["Memphis Grizzlies","Los Angeles Lakers","Chicago Bulls","San Antonio Spurs","Milwaukee Bucks","Portland Trail Blazers"],difficulty:3},
  {name:"Amare Stoudemire",teams:["Phoenix Suns","New York Knicks","Dallas Mavericks","Miami Heat"],difficulty:3},
  {name:"Ben Wallace",teams:["Washington Wizards","Orlando Magic","Detroit Pistons","Chicago Bulls","Cleveland Cavaliers","Detroit Pistons"],difficulty:3},
  {name:"Rasheed Wallace",teams:["Washington Wizards","Portland Trail Blazers","Atlanta Hawks","Detroit Pistons","Boston Celtics"],difficulty:3},
  {name:"Baron Davis",teams:["Charlotte Hornets","New Orleans Pelicans","Golden State Warriors","Los Angeles Clippers","Cleveland Cavaliers","New York Knicks"],difficulty:3},
  {name:"Zach Randolph",teams:["Portland Trail Blazers","New York Knicks","Los Angeles Clippers","Memphis Grizzlies","Sacramento Kings"],difficulty:4},
  {name:"Jamal Crawford",teams:["Chicago Bulls","New York Knicks","Golden State Warriors","Atlanta Hawks","Portland Trail Blazers","Los Angeles Clippers","Minnesota Timberwolves","Phoenix Suns","Brooklyn Nets"],difficulty:4},
  {name:"Rudy Gay",teams:["Memphis Grizzlies","Toronto Raptors","Sacramento Kings","San Antonio Spurs","Utah Jazz"],difficulty:4},
  {name:"Jeff Green",teams:["Oklahoma City Thunder","Boston Celtics","Memphis Grizzlies","Los Angeles Clippers","Orlando Magic","Cleveland Cavaliers","Washington Wizards","Houston Rockets","Brooklyn Nets","Denver Nuggets"],difficulty:4},
  {name:"Richard Jefferson",teams:["New Jersey Nets","Milwaukee Bucks","San Antonio Spurs","Golden State Warriors","Utah Jazz","Dallas Mavericks","Cleveland Cavaliers","Denver Nuggets"],difficulty:4},
  {name:"Ish Smith",teams:["Houston Rockets","Memphis Grizzlies","Orlando Magic","Milwaukee Bucks","Phoenix Suns","Oklahoma City Thunder","Philadelphia 76ers","Detroit Pistons","Washington Wizards","Charlotte Hornets","San Antonio Spurs","Denver Nuggets"],difficulty:5},
  {name:"Robin Lopez",teams:["Phoenix Suns","New Orleans Pelicans","Portland Trail Blazers","New York Knicks","Chicago Bulls","Milwaukee Bucks","Washington Wizards","Orlando Magic","Cleveland Cavaliers"],difficulty:4},
  {name:"Isaiah Thomas",teams:["Sacramento Kings","Phoenix Suns","Boston Celtics","Cleveland Cavaliers","Los Angeles Lakers","Denver Nuggets","Washington Wizards","Minnesota Timberwolves","Charlotte Hornets","Dallas Mavericks"],difficulty:4},
  {name:"Trevor Ariza",teams:["New York Knicks","Orlando Magic","Los Angeles Lakers","Houston Rockets","New Orleans Pelicans","Washington Wizards","Phoenix Suns","Sacramento Kings","Portland Trail Blazers","Houston Rockets","Miami Heat"],difficulty:5},
  {name:"Lou Williams",teams:["Philadelphia 76ers","Atlanta Hawks","Toronto Raptors","Los Angeles Lakers","Houston Rockets","Los Angeles Clippers","Atlanta Hawks"],difficulty:4},
  {name:"DeAndre Jordan",teams:["Los Angeles Clippers","Dallas Mavericks","New York Knicks","Brooklyn Nets","Los Angeles Lakers","Philadelphia 76ers","Denver Nuggets"],difficulty:4},
  {name:"Spencer Dinwiddie",teams:["Detroit Pistons","Brooklyn Nets","Washington Wizards","Dallas Mavericks","Brooklyn Nets","Los Angeles Lakers","Toronto Raptors"],difficulty:4},
  {name:"Goran Dragic",teams:["Phoenix Suns","Houston Rockets","Phoenix Suns","Miami Heat","Toronto Raptors","Brooklyn Nets","Milwaukee Bucks","Chicago Bulls"],difficulty:4},
  {name:"Marcus Morris",teams:["Houston Rockets","Phoenix Suns","Detroit Pistons","Boston Celtics","San Antonio Spurs","New York Knicks","Los Angeles Clippers"],difficulty:5},
  {name:"Thaddeus Young",teams:["Philadelphia 76ers","Minnesota Timberwolves","Brooklyn Nets","Indiana Pacers","Chicago Bulls","San Antonio Spurs","Toronto Raptors","Phoenix Suns"],difficulty:5},
  {name:"George Hill",teams:["San Antonio Spurs","Indiana Pacers","Utah Jazz","Sacramento Kings","Cleveland Cavaliers","Milwaukee Bucks","Oklahoma City Thunder","Philadelphia 76ers"],difficulty:5},
];
