// NFL Career Path data — curated notable retired players
// Teams listed in CHRONOLOGICAL order (career progression)
// Last updated: February 2026

export const NFL_CAREER_PATHS = [
  // ── Quarterbacks ──
  {name:"Tom Brady",teams:["New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Peyton Manning",teams:["Indianapolis Colts","Denver Broncos"]},
  {name:"Brett Favre",teams:["Atlanta Falcons","Green Bay Packers","New York Jets","Minnesota Vikings"]},
  {name:"Drew Brees",teams:["San Diego Chargers","New Orleans Saints"]},
  {name:"Joe Montana",teams:["San Francisco 49ers","Kansas City Chiefs"]},
  {name:"Steve Young",teams:["Tampa Bay Buccaneers","San Francisco 49ers"]},
  {name:"Warren Moon",teams:["Houston Oilers","Minnesota Vikings","Seattle Seahawks","Kansas City Chiefs"]},
  {name:"Matt Ryan",teams:["Atlanta Falcons","Indianapolis Colts"]},
  {name:"Philip Rivers",teams:["San Diego Chargers","Indianapolis Colts"]},
  {name:"Carson Palmer",teams:["Cincinnati Bengals","Oakland Raiders","Arizona Cardinals"]},
  {name:"Kurt Warner",teams:["St. Louis Rams","New York Giants","Arizona Cardinals"]},
  {name:"Donovan McNabb",teams:["Philadelphia Eagles","Washington Redskins","Minnesota Vikings"]},
  {name:"Michael Vick",teams:["Atlanta Falcons","Philadelphia Eagles","New York Jets","Pittsburgh Steelers"]},
  {name:"Cam Newton",teams:["Carolina Panthers","New England Patriots"]},
  {name:"Alex Smith",teams:["San Francisco 49ers","Kansas City Chiefs","Washington Commanders"]},
  {name:"Sam Bradford",teams:["St. Louis Rams","Philadelphia Eagles","Minnesota Vikings","Arizona Cardinals"]},
  {name:"Jay Cutler",teams:["Denver Broncos","Chicago Bears","Miami Dolphins"]},
  {name:"Matthew Stafford",teams:["Detroit Lions","Los Angeles Rams"]},
  {name:"Ryan Fitzpatrick",teams:["St. Louis Rams","Cincinnati Bengals","Buffalo Bills","Tennessee Titans","Houston Texans","New York Jets","Tampa Bay Buccaneers","Miami Dolphins","Washington Commanders"]},
  {name:"Josh McCown",teams:["Arizona Cardinals","Detroit Lions","Oakland Raiders","Miami Dolphins","Carolina Panthers","Chicago Bears","Tampa Bay Buccaneers","Cleveland Browns","New York Jets","Philadelphia Eagles"]},
  {name:"Vinny Testaverde",teams:["Tampa Bay Buccaneers","Cleveland Browns","Baltimore Ravens","New York Jets","Dallas Cowboys","New England Patriots","Carolina Panthers"]},
  {name:"Kerry Collins",teams:["Carolina Panthers","New Orleans Saints","New York Giants","Oakland Raiders","Tennessee Titans","Indianapolis Colts"]},
  {name:"Jeff Garcia",teams:["San Francisco 49ers","Cleveland Browns","Detroit Lions","Philadelphia Eagles","Tampa Bay Buccaneers"]},
  {name:"Rich Gannon",teams:["Minnesota Vikings","Washington Redskins","Kansas City Chiefs","Oakland Raiders"]},
  {name:"Drew Bledsoe",teams:["New England Patriots","Buffalo Bills","Dallas Cowboys"]},
  {name:"Randall Cunningham",teams:["Philadelphia Eagles","Minnesota Vikings","Dallas Cowboys","Baltimore Ravens"]},
  {name:"Steve McNair",teams:["Tennessee Titans","Baltimore Ravens"]},
  {name:"Daunte Culpepper",teams:["Minnesota Vikings","Miami Dolphins","Oakland Raiders","Detroit Lions"]},
  {name:"Chad Pennington",teams:["New York Jets","Miami Dolphins"]},
  {name:"Matt Hasselbeck",teams:["Green Bay Packers","Seattle Seahawks","Tennessee Titans","Indianapolis Colts"]},
  {name:"Mark Brunell",teams:["Green Bay Packers","Jacksonville Jaguars","Washington Redskins","New Orleans Saints","New York Jets"]},
  {name:"Jim Plunkett",teams:["New England Patriots","San Francisco 49ers","Oakland Raiders"]},
  {name:"Matt Schaub",teams:["Atlanta Falcons","Houston Texans","Oakland Raiders","Baltimore Ravens"]},
  {name:"Mark Sanchez",teams:["New York Jets","Philadelphia Eagles","Dallas Cowboys","Chicago Bears","Washington Redskins"]},
  {name:"Robert Griffin III",teams:["Washington Redskins","Cleveland Browns","Baltimore Ravens"]},
  {name:"Teddy Bridgewater",teams:["Minnesota Vikings","New Orleans Saints","Carolina Panthers","Denver Broncos","Miami Dolphins","Detroit Lions"]},

  // ── Running Backs ──
  {name:"Emmitt Smith",teams:["Dallas Cowboys","Arizona Cardinals"]},
  {name:"Eric Dickerson",teams:["Los Angeles Rams","Indianapolis Colts","Los Angeles Raiders","Atlanta Falcons"]},
  {name:"LaDainian Tomlinson",teams:["San Diego Chargers","New York Jets"]},
  {name:"Adrian Peterson",teams:["Minnesota Vikings","New Orleans Saints","Arizona Cardinals","Washington Redskins","Detroit Lions","Tennessee Titans","Seattle Seahawks"]},
  {name:"Frank Gore",teams:["San Francisco 49ers","Indianapolis Colts","Miami Dolphins","Buffalo Bills","New York Jets"]},
  {name:"Marshawn Lynch",teams:["Buffalo Bills","Seattle Seahawks","Oakland Raiders"]},
  {name:"DeMarco Murray",teams:["Dallas Cowboys","Philadelphia Eagles","Tennessee Titans"]},
  {name:"Todd Gurley",teams:["St. Louis Rams","Atlanta Falcons"]},
  {name:"Arian Foster",teams:["Houston Texans","Miami Dolphins"]},
  {name:"Chris Johnson",teams:["Tennessee Titans","New York Jets","Arizona Cardinals"]},
  {name:"Maurice Jones-Drew",teams:["Jacksonville Jaguars","Oakland Raiders"]},
  {name:"Edgerrin James",teams:["Indianapolis Colts","Arizona Cardinals","Seattle Seahawks"]},
  {name:"Fred Taylor",teams:["Jacksonville Jaguars","New England Patriots"]},
  {name:"Ricky Williams",teams:["New Orleans Saints","Miami Dolphins","Baltimore Ravens"]},
  {name:"Corey Dillon",teams:["Cincinnati Bengals","New England Patriots"]},
  {name:"Clinton Portis",teams:["Denver Broncos","Washington Redskins"]},
  {name:"Thomas Jones",teams:["Arizona Cardinals","Tampa Bay Buccaneers","Chicago Bears","New York Jets","Kansas City Chiefs"]},
  {name:"Willis McGahee",teams:["Buffalo Bills","Baltimore Ravens","Denver Broncos","Cleveland Browns"]},
  {name:"Jamal Lewis",teams:["Baltimore Ravens","Cleveland Browns"]},
  {name:"Steven Jackson",teams:["St. Louis Rams","Atlanta Falcons","New England Patriots"]},
  {name:"Shaun Alexander",teams:["Seattle Seahawks","Washington Redskins"]},
  {name:"Curtis Martin",teams:["New England Patriots","New York Jets"]},
  {name:"Jerome Bettis",teams:["Los Angeles Rams","Pittsburgh Steelers"]},
  {name:"Marshall Faulk",teams:["Indianapolis Colts","St. Louis Rams"]},
  {name:"Eddie George",teams:["Tennessee Titans","Dallas Cowboys"]},
  {name:"Priest Holmes",teams:["Baltimore Ravens","Kansas City Chiefs"]},
  {name:"Warrick Dunn",teams:["Tampa Bay Buccaneers","Atlanta Falcons"]},
  {name:"Thurman Thomas",teams:["Buffalo Bills","Miami Dolphins"]},
  {name:"Marcus Allen",teams:["Los Angeles Raiders","Kansas City Chiefs"]},
  {name:"Franco Harris",teams:["Pittsburgh Steelers","Seattle Seahawks"]},
  {name:"Earl Campbell",teams:["Houston Oilers","New Orleans Saints"]},
  {name:"Tony Dorsett",teams:["Dallas Cowboys","Denver Broncos"]},
  {name:"O.J. Simpson",teams:["Buffalo Bills","San Francisco 49ers"]},
  {name:"Matt Forte",teams:["Chicago Bears","New York Jets"]},
  {name:"Reggie Bush",teams:["New Orleans Saints","Miami Dolphins","Detroit Lions","San Francisco 49ers","Buffalo Bills"]},
  {name:"Knowshon Moreno",teams:["Denver Broncos","Miami Dolphins"]},
  {name:"Carlos Hyde",teams:["San Francisco 49ers","Cleveland Browns","Jacksonville Jaguars","Seattle Seahawks"]},
  {name:"Danny Woodhead",teams:["New York Jets","New England Patriots","San Diego Chargers","Baltimore Ravens"]},
  {name:"James White",teams:["New England Patriots","San Francisco 49ers"]},
  {name:"LeGarrette Blount",teams:["Tampa Bay Buccaneers","New England Patriots","Pittsburgh Steelers","New England Patriots","Philadelphia Eagles","Detroit Lions"]},

  // ── Wide Receivers ──
  {name:"Jerry Rice",teams:["San Francisco 49ers","Oakland Raiders","Seattle Seahawks"]},
  {name:"Randy Moss",teams:["Minnesota Vikings","Oakland Raiders","New England Patriots","Minnesota Vikings","Tennessee Titans","San Francisco 49ers"]},
  {name:"Terrell Owens",teams:["San Francisco 49ers","Philadelphia Eagles","Dallas Cowboys","Buffalo Bills","Cincinnati Bengals"]},
  {name:"Antonio Brown",teams:["Pittsburgh Steelers","Oakland Raiders","New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Julio Jones",teams:["Atlanta Falcons","Tennessee Titans","Tampa Bay Buccaneers"]},
  {name:"Dez Bryant",teams:["Dallas Cowboys","New Orleans Saints"]},
  {name:"Demaryius Thomas",teams:["Denver Broncos","Houston Texans","New England Patriots","New York Jets"]},
  {name:"Brandon Marshall",teams:["Denver Broncos","Miami Dolphins","Chicago Bears","New York Jets","New York Giants","Seattle Seahawks","New Orleans Saints"]},
  {name:"Wes Welker",teams:["San Diego Chargers","Miami Dolphins","New England Patriots","Denver Broncos"]},
  {name:"Steve Smith",teams:["Carolina Panthers","Baltimore Ravens"]},
  {name:"Andre Johnson",teams:["Houston Texans","Indianapolis Colts","Tennessee Titans"]},
  {name:"Anquan Boldin",teams:["Arizona Cardinals","Baltimore Ravens","San Francisco 49ers","Detroit Lions"]},
  {name:"Isaac Bruce",teams:["Los Angeles Rams","San Francisco 49ers"]},
  {name:"Torry Holt",teams:["St. Louis Rams","Jacksonville Jaguars"]},
  {name:"Tim Brown",teams:["Los Angeles Raiders","Tampa Bay Buccaneers"]},
  {name:"Cris Carter",teams:["Philadelphia Eagles","Minnesota Vikings","Miami Dolphins"]},
  {name:"Art Monk",teams:["Washington Redskins","New York Jets","Philadelphia Eagles"]},
  {name:"James Lofton",teams:["Green Bay Packers","Los Angeles Raiders","Buffalo Bills","Los Angeles Rams","Philadelphia Eagles"]},
  {name:"Chad Johnson",teams:["Cincinnati Bengals","New England Patriots","Miami Dolphins"]},
  {name:"Santana Moss",teams:["New York Jets","Washington Redskins"]},
  {name:"DeSean Jackson",teams:["Philadelphia Eagles","Washington Redskins","Tampa Bay Buccaneers","Philadelphia Eagles","Los Angeles Rams","Las Vegas Raiders"]},
  {name:"Pierre Garcon",teams:["Indianapolis Colts","Washington Redskins","San Francisco 49ers"]},
  {name:"Eric Decker",teams:["Denver Broncos","New York Jets","Tennessee Titans","New England Patriots"]},
  {name:"Golden Tate",teams:["Seattle Seahawks","Detroit Lions","Philadelphia Eagles","New York Giants"]},
  {name:"Emmanuel Sanders",teams:["Pittsburgh Steelers","Denver Broncos","San Francisco 49ers","New Orleans Saints","Buffalo Bills"]},
  {name:"Danny Amendola",teams:["St. Louis Rams","New England Patriots","Miami Dolphins","Detroit Lions","Houston Texans"]},
  {name:"Kenny Stills",teams:["New Orleans Saints","Miami Dolphins","Houston Texans"]},
  {name:"Mohamed Sanu",teams:["Cincinnati Bengals","Atlanta Falcons","New England Patriots","San Francisco 49ers","Detroit Lions"]},

  // ── Tight Ends ──
  {name:"Tony Gonzalez",teams:["Kansas City Chiefs","Atlanta Falcons"]},
  {name:"Rob Gronkowski",teams:["New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Jason Witten",teams:["Dallas Cowboys","Las Vegas Raiders"]},
  {name:"Shannon Sharpe",teams:["Denver Broncos","Baltimore Ravens","Denver Broncos"]},
  {name:"Jimmy Graham",teams:["New Orleans Saints","Seattle Seahawks","Green Bay Packers","Chicago Bears"]},
  {name:"Greg Olsen",teams:["Chicago Bears","Carolina Panthers","Seattle Seahawks"]},
  {name:"Vernon Davis",teams:["San Francisco 49ers","Denver Broncos","Washington Redskins"]},
  {name:"Dallas Clark",teams:["Indianapolis Colts","Tampa Bay Buccaneers","Baltimore Ravens"]},
  {name:"Martellus Bennett",teams:["Dallas Cowboys","New York Giants","Chicago Bears","New England Patriots","Green Bay Packers"]},
  {name:"Delanie Walker",teams:["San Francisco 49ers","Tennessee Titans"]},
  {name:"Owen Daniels",teams:["Houston Texans","Baltimore Ravens","Denver Broncos"]},

  // ── Offensive Linemen ──
  {name:"Larry Allen",teams:["Dallas Cowboys","San Francisco 49ers"]},
  {name:"Orlando Pace",teams:["St. Louis Rams","Chicago Bears"]},
  {name:"Randall McDaniel",teams:["Minnesota Vikings","Tampa Bay Buccaneers"]},
  {name:"Alan Faneca",teams:["Pittsburgh Steelers","New York Jets","Arizona Cardinals"]},
  {name:"Steve Hutchinson",teams:["Seattle Seahawks","Minnesota Vikings","Tennessee Titans"]},
  {name:"Kevin Mawae",teams:["Seattle Seahawks","New York Jets","Tennessee Titans"]},
  {name:"Mike Webster",teams:["Pittsburgh Steelers","Kansas City Chiefs"]},
  {name:"Andrew Whitworth",teams:["Cincinnati Bengals","Los Angeles Rams"]},
  {name:"Jeff Saturday",teams:["Indianapolis Colts","Green Bay Packers"]},
  {name:"Logan Mankins",teams:["New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Richie Incognito",teams:["St. Louis Rams","Miami Dolphins","Buffalo Bills","Oakland Raiders"]},

  // ── Defensive Linemen ──
  {name:"Reggie White",teams:["Philadelphia Eagles","Green Bay Packers","Carolina Panthers"]},
  {name:"Bruce Smith",teams:["Buffalo Bills","Washington Redskins"]},
  {name:"J.J. Watt",teams:["Houston Texans","Arizona Cardinals"]},
  {name:"Julius Peppers",teams:["Carolina Panthers","Chicago Bears","Green Bay Packers","Carolina Panthers"]},
  {name:"Jason Taylor",teams:["Miami Dolphins","Washington Redskins","New York Jets","Miami Dolphins"]},
  {name:"Dwight Freeney",teams:["Indianapolis Colts","San Diego Chargers","Arizona Cardinals","Atlanta Falcons","Detroit Lions","Seattle Seahawks"]},
  {name:"Richard Dent",teams:["Chicago Bears","San Francisco 49ers","Indianapolis Colts","Philadelphia Eagles"]},
  {name:"John Randle",teams:["Minnesota Vikings","Seattle Seahawks"]},
  {name:"Warren Sapp",teams:["Tampa Bay Buccaneers","Oakland Raiders"]},
  {name:"Gerald McCoy",teams:["Tampa Bay Buccaneers","Carolina Panthers","Dallas Cowboys"]},
  {name:"Vince Wilfork",teams:["New England Patriots","Houston Texans"]},
  {name:"Haloti Ngata",teams:["Baltimore Ravens","Detroit Lions","Philadelphia Eagles"]},
  {name:"Justin Smith",teams:["Cincinnati Bengals","San Francisco 49ers"]},
  {name:"Chris Long",teams:["St. Louis Rams","New England Patriots","Philadelphia Eagles"]},
  {name:"Cameron Wake",teams:["Miami Dolphins","Tennessee Titans"]},
  {name:"DeMarcus Ware",teams:["Dallas Cowboys","Denver Broncos"]},
  {name:"Justin Tuck",teams:["New York Giants","Oakland Raiders"]},
  {name:"Jared Allen",teams:["Kansas City Chiefs","Minnesota Vikings","Chicago Bears","Carolina Panthers"]},
  {name:"John Abraham",teams:["New York Jets","Atlanta Falcons","Arizona Cardinals"]},

  // ── Linebackers ──
  {name:"Junior Seau",teams:["San Diego Chargers","Miami Dolphins","New England Patriots"]},
  {name:"Terrell Suggs",teams:["Baltimore Ravens","Arizona Cardinals","Kansas City Chiefs"]},
  {name:"James Harrison",teams:["Pittsburgh Steelers","Cincinnati Bengals","New England Patriots"]},
  {name:"Thomas Davis",teams:["Carolina Panthers","Los Angeles Chargers","Washington Commanders"]},
  {name:"Jamie Collins",teams:["New England Patriots","Cleveland Browns","New England Patriots","Detroit Lions"]},
  {name:"Danny Trevathan",teams:["Denver Broncos","Chicago Bears"]},
  {name:"Zach Thomas",teams:["Miami Dolphins","Dallas Cowboys"]},
  {name:"London Fletcher",teams:["St. Louis Rams","Buffalo Bills","Washington Redskins"]},
  {name:"Keith Brooking",teams:["Atlanta Falcons","Dallas Cowboys","Denver Broncos"]},
  {name:"Takeo Spikes",teams:["Cincinnati Bengals","Buffalo Bills","Philadelphia Eagles","San Francisco 49ers","San Diego Chargers"]},
  {name:"Clay Matthews",teams:["Green Bay Packers","Los Angeles Rams"]},

  // ── Defensive Backs ──
  {name:"Deion Sanders",teams:["Atlanta Falcons","San Francisco 49ers","Dallas Cowboys","Washington Redskins","Baltimore Ravens"]},
  {name:"Rod Woodson",teams:["Pittsburgh Steelers","San Francisco 49ers","Baltimore Ravens","Oakland Raiders"]},
  {name:"Charles Woodson",teams:["Oakland Raiders","Green Bay Packers","Oakland Raiders"]},
  {name:"Ed Reed",teams:["Baltimore Ravens","Houston Texans","New York Jets"]},
  {name:"Champ Bailey",teams:["Washington Redskins","Denver Broncos","New Orleans Saints"]},
  {name:"Darrelle Revis",teams:["New York Jets","Tampa Bay Buccaneers","New England Patriots","New York Jets","Kansas City Chiefs"]},
  {name:"Richard Sherman",teams:["Seattle Seahawks","San Francisco 49ers","Tampa Bay Buccaneers"]},
  {name:"Ty Law",teams:["New England Patriots","New York Jets","Kansas City Chiefs","Denver Broncos"]},
  {name:"Aeneas Williams",teams:["Arizona Cardinals","St. Louis Rams"]},
  {name:"Brian Dawkins",teams:["Philadelphia Eagles","Denver Broncos"]},
  {name:"John Lynch",teams:["Tampa Bay Buccaneers","Denver Broncos"]},
  {name:"Darren Sharper",teams:["Green Bay Packers","Minnesota Vikings","New Orleans Saints"]},
  {name:"Asante Samuel",teams:["New England Patriots","Philadelphia Eagles","Atlanta Falcons"]},
  {name:"Aqib Talib",teams:["Tampa Bay Buccaneers","New England Patriots","Denver Broncos","Los Angeles Rams","Miami Dolphins"]},
  {name:"Malcolm Jenkins",teams:["New Orleans Saints","Philadelphia Eagles","New Orleans Saints"]},
  {name:"Eric Weddle",teams:["San Diego Chargers","Baltimore Ravens","Los Angeles Rams"]},
  {name:"Terence Newman",teams:["Dallas Cowboys","Cincinnati Bengals","Minnesota Vikings"]},
  {name:"Antoine Bethea",teams:["Indianapolis Colts","San Francisco 49ers","Arizona Cardinals","New York Giants"]},
  {name:"Glover Quin",teams:["Houston Texans","Detroit Lions"]},
  {name:"Joe Haden",teams:["Cleveland Browns","Pittsburgh Steelers"]},

  // ── Specialists ──
  {name:"Adam Vinatieri",teams:["New England Patriots","Indianapolis Colts"]},
  {name:"Morten Andersen",teams:["New Orleans Saints","Atlanta Falcons","New York Giants","Kansas City Chiefs","Minnesota Vikings"]},
  {name:"Matt Bryant",teams:["New York Giants","Tampa Bay Buccaneers","Atlanta Falcons"]},
  {name:"Sebastian Janikowski",teams:["Oakland Raiders","Seattle Seahawks"]},
  {name:"Stephen Gostkowski",teams:["New England Patriots","Tennessee Titans"]},
  {name:"Phil Dawson",teams:["Cleveland Browns","San Francisco 49ers","Arizona Cardinals"]},
  {name:"Josh Brown",teams:["Seattle Seahawks","St. Louis Rams","Cincinnati Bengals","New York Giants"]},
];
