// NFL Career Path Quiz - Player data
// Each player has teams in chronological order of their career
// difficulty: 1 (easy - famous journeys) to 5 (hard - obscure paths)

export const NFL_CAREER_PATHS = [
  // Easy - iconic journeys
  {name:"Tom Brady",teams:["New England Patriots","Tampa Bay Buccaneers"],difficulty:1},
  {name:"Peyton Manning",teams:["Indianapolis Colts","Denver Broncos"],difficulty:1},
  {name:"Brett Favre",teams:["Atlanta Falcons","Green Bay Packers","New York Jets","Minnesota Vikings"],difficulty:1},
  {name:"Joe Montana",teams:["San Francisco 49ers","Kansas City Chiefs"],difficulty:1},
  {name:"Jerry Rice",teams:["San Francisco 49ers","Oakland Raiders","Seattle Seahawks","Denver Broncos"],difficulty:1},
  {name:"Deion Sanders",teams:["Atlanta Falcons","San Francisco 49ers","Dallas Cowboys","Washington Redskins","Baltimore Ravens"],difficulty:1},
  {name:"Randy Moss",teams:["Minnesota Vikings","Oakland Raiders","New England Patriots","Minnesota Vikings","San Francisco 49ers"],difficulty:1},
  {name:"Terrell Owens",teams:["San Francisco 49ers","Philadelphia Eagles","Dallas Cowboys","Buffalo Bills","Cincinnati Bengals"],difficulty:1},
  {name:"Darrelle Revis",teams:["New York Jets","Tampa Bay Buccaneers","New England Patriots","New York Jets","Kansas City Chiefs"],difficulty:1},
  {name:"Le'Veon Bell",teams:["Pittsburgh Steelers","New York Jets","Kansas City Chiefs","Baltimore Ravens","Tampa Bay Buccaneers"],difficulty:2},
  {name:"DeAndre Hopkins",teams:["Houston Texans","Arizona Cardinals","Tennessee Titans","New England Patriots"],difficulty:1},
  {name:"Russell Wilson",teams:["Seattle Seahawks","Denver Broncos","Pittsburgh Steelers"],difficulty:1},
  {name:"Stefon Diggs",teams:["Minnesota Vikings","Buffalo Bills","Houston Texans"],difficulty:1},
  {name:"Odell Beckham Jr.",teams:["New York Giants","Cleveland Browns","Los Angeles Rams","Baltimore Ravens","Miami Dolphins"],difficulty:1},
  {name:"Adrian Peterson",teams:["Minnesota Vikings","New Orleans Saints","Arizona Cardinals","Washington Redskins","Detroit Lions","Tennessee Titans","Seattle Seahawks"],difficulty:1},
  {name:"Marshawn Lynch",teams:["Buffalo Bills","Seattle Seahawks","Oakland Raiders"],difficulty:1},
  {name:"Julio Jones",teams:["Atlanta Falcons","Tennessee Titans","Tampa Bay Buccaneers"],difficulty:2},
  {name:"Calvin Ridley",teams:["Atlanta Falcons","Jacksonville Jaguars","Tennessee Titans"],difficulty:2},
  {name:"Matthew Stafford",teams:["Detroit Lions","Los Angeles Rams"],difficulty:1},
  {name:"Carson Palmer",teams:["Cincinnati Bengals","Oakland Raiders","Arizona Cardinals"],difficulty:2},
  // Medium
  {name:"Drew Brees",teams:["San Diego Chargers","New Orleans Saints"],difficulty:1},
  {name:"Sam Bradford",teams:["St. Louis Rams","Philadelphia Eagles","Minnesota Vikings","Arizona Cardinals"],difficulty:2},
  {name:"Ryan Tannehill",teams:["Miami Dolphins","Tennessee Titans"],difficulty:2},
  {name:"Jay Cutler",teams:["Denver Broncos","Chicago Bears","Miami Dolphins"],difficulty:2},
  {name:"Alex Smith",teams:["San Francisco 49ers","Kansas City Chiefs","Washington Redskins"],difficulty:2},
  {name:"Nick Foles",teams:["Philadelphia Eagles","St. Louis Rams","Kansas City Chiefs","Philadelphia Eagles","Jacksonville Jaguars","Chicago Bears","Indianapolis Colts"],difficulty:2},
  {name:"Ryan Fitzpatrick",teams:["St. Louis Rams","Cincinnati Bengals","Buffalo Bills","Tennessee Titans","Houston Texans","New York Jets","Tampa Bay Buccaneers","Miami Dolphins","Washington Football Team"],difficulty:2},
  {name:"Josh McCown",teams:["Arizona Cardinals","Detroit Lions","Oakland Raiders","Miami Dolphins","Carolina Panthers","Chicago Bears","Tampa Bay Buccaneers","Cleveland Browns","New York Jets","Philadelphia Eagles"],difficulty:3},
  {name:"Tyreek Hill",teams:["Kansas City Chiefs","Miami Dolphins"],difficulty:1},
  {name:"Davante Adams",teams:["Green Bay Packers","Las Vegas Raiders","New York Jets"],difficulty:1},
  {name:"A.J. Green",teams:["Cincinnati Bengals","Arizona Cardinals"],difficulty:2},
  {name:"Brandon Marshall",teams:["Denver Broncos","Miami Dolphins","Chicago Bears","New York Jets","New York Giants","Seattle Seahawks"],difficulty:2},
  {name:"Brandin Cooks",teams:["New Orleans Saints","New England Patriots","Los Angeles Rams","Houston Texans","Dallas Cowboys"],difficulty:2},
  {name:"Emmanuel Sanders",teams:["Pittsburgh Steelers","Denver Broncos","San Francisco 49ers","New Orleans Saints","Buffalo Bills"],difficulty:2},
  {name:"DeSean Jackson",teams:["Philadelphia Eagles","Washington Redskins","Tampa Bay Buccaneers","Philadelphia Eagles","Los Angeles Rams","Las Vegas Raiders"],difficulty:2},
  {name:"Amari Cooper",teams:["Oakland Raiders","Dallas Cowboys","Cleveland Browns","Buffalo Bills"],difficulty:2},
  {name:"DeMarco Murray",teams:["Dallas Cowboys","Philadelphia Eagles","Tennessee Titans"],difficulty:2},
  {name:"LeSean McCoy",teams:["Philadelphia Eagles","Buffalo Bills","Kansas City Chiefs","Tampa Bay Buccaneers"],difficulty:2},
  {name:"Frank Gore",teams:["San Francisco 49ers","Indianapolis Colts","Miami Dolphins","Buffalo Bills","New York Jets"],difficulty:2},
  {name:"Kareem Hunt",teams:["Kansas City Chiefs","Cleveland Browns"],difficulty:2},
  {name:"Melvin Gordon",teams:["San Diego Chargers","Denver Broncos"],difficulty:2},
  // Harder
  {name:"Charles Woodson",teams:["Oakland Raiders","Green Bay Packers","Oakland Raiders"],difficulty:2},
  {name:"Aqib Talib",teams:["Tampa Bay Buccaneers","New England Patriots","Denver Broncos","Los Angeles Rams","Miami Dolphins"],difficulty:3},
  {name:"Richard Sherman",teams:["Seattle Seahawks","San Francisco 49ers","Tampa Bay Buccaneers"],difficulty:2},
  {name:"Patrick Peterson",teams:["Arizona Cardinals","Minnesota Vikings","Pittsburgh Steelers"],difficulty:2},
  {name:"Stephon Gilmore",teams:["Buffalo Bills","New England Patriots","Carolina Panthers","Indianapolis Colts","Dallas Cowboys","Minnesota Vikings"],difficulty:3},
  {name:"Khalil Mack",teams:["Oakland Raiders","Chicago Bears","Los Angeles Chargers"],difficulty:2},
  {name:"Von Miller",teams:["Denver Broncos","Los Angeles Rams","Buffalo Bills"],difficulty:2},
  {name:"Chandler Jones",teams:["New England Patriots","Arizona Cardinals","Las Vegas Raiders"],difficulty:3},
  {name:"Jadeveon Clowney",teams:["Houston Texans","Seattle Seahawks","Tennessee Titans","Cleveland Browns","Baltimore Ravens","Carolina Panthers"],difficulty:3},
  {name:"J.J. Watt",teams:["Houston Texans","Arizona Cardinals"],difficulty:1},
  {name:"Ndamukong Suh",teams:["Detroit Lions","Miami Dolphins","Los Angeles Rams","Tampa Bay Buccaneers","Philadelphia Eagles"],difficulty:3},
  {name:"Calais Campbell",teams:["Arizona Cardinals","Jacksonville Jaguars","Baltimore Ravens","Atlanta Falcons","Miami Dolphins"],difficulty:3},
  {name:"Jason Pierre-Paul",teams:["New York Giants","Tampa Bay Buccaneers","Baltimore Ravens","Miami Dolphins"],difficulty:3},
  {name:"Julius Peppers",teams:["Carolina Panthers","Chicago Bears","Green Bay Packers","Carolina Panthers"],difficulty:3},
  {name:"Derrick Henry",teams:["Tennessee Titans","Baltimore Ravens"],difficulty:1},
  {name:"Saquon Barkley",teams:["New York Giants","Philadelphia Eagles"],difficulty:1},
  {name:"Josh Jacobs",teams:["Las Vegas Raiders","Green Bay Packers"],difficulty:2},
  {name:"Austin Ekeler",teams:["Los Angeles Chargers","Washington Commanders"],difficulty:2},
  {name:"Raheem Mostert",teams:["Cleveland Browns","San Francisco 49ers","Miami Dolphins"],difficulty:3},
  {name:"Cordarrelle Patterson",teams:["Minnesota Vikings","Oakland Raiders","New England Patriots","Chicago Bears","Atlanta Falcons","Pittsburgh Steelers"],difficulty:3},
  {name:"Antonio Brown",teams:["Pittsburgh Steelers","Oakland Raiders","New England Patriots","Tampa Bay Buccaneers"],difficulty:2},
  {name:"Kelvin Benjamin",teams:["Carolina Panthers","Buffalo Bills","Kansas City Chiefs","New York Giants"],difficulty:3},
  {name:"Robert Quinn",teams:["St. Louis Rams","Miami Dolphins","Dallas Cowboys","Chicago Bears","Philadelphia Eagles"],difficulty:4},
  {name:"Jamal Adams",teams:["New York Jets","Seattle Seahawks","Tennessee Titans"],difficulty:3},
  {name:"Earl Thomas",teams:["Seattle Seahawks","Baltimore Ravens"],difficulty:2},
  {name:"Eric Berry",teams:["Kansas City Chiefs"],difficulty:2},
  {name:"Tyrann Mathieu",teams:["Arizona Cardinals","Houston Texans","Kansas City Chiefs","New Orleans Saints"],difficulty:3},
  {name:"Landon Collins",teams:["New York Giants","Washington Redskins","New York Giants"],difficulty:3},
  {name:"Dez Bryant",teams:["Dallas Cowboys","New Orleans Saints","Baltimore Ravens"],difficulty:2},
  {name:"Golden Tate",teams:["Seattle Seahawks","Detroit Lions","Philadelphia Eagles","New York Giants"],difficulty:3},
  {name:"Randall Cobb",teams:["Green Bay Packers","Dallas Cowboys","Houston Texans","Green Bay Packers","New York Jets"],difficulty:3},
  {name:"Ted Ginn Jr.",teams:["Miami Dolphins","San Francisco 49ers","Carolina Panthers","Arizona Cardinals","New Orleans Saints","Chicago Bears"],difficulty:4},
  {name:"Percy Harvin",teams:["Minnesota Vikings","Seattle Seahawks","New York Jets","Buffalo Bills"],difficulty:3},
  {name:"Wes Welker",teams:["San Diego Chargers","Miami Dolphins","New England Patriots","Denver Broncos"],difficulty:3},
  {name:"Eric Weddle",teams:["San Diego Chargers","Baltimore Ravens","Los Angeles Rams"],difficulty:3},
  {name:"Kirk Cousins",teams:["Washington Redskins","Minnesota Vikings","Atlanta Falcons"],difficulty:2},
  {name:"Case Keenum",teams:["Houston Texans","St. Louis Rams","Minnesota Vikings","Denver Broncos","Washington Redskins","Cleveland Browns","Buffalo Bills"],difficulty:4},
  {name:"Teddy Bridgewater",teams:["Minnesota Vikings","New Orleans Saints","Carolina Panthers","Denver Broncos","Miami Dolphins","Detroit Lions"],difficulty:3},
  {name:"Joe Flacco",teams:["Baltimore Ravens","Denver Broncos","New York Jets","Philadelphia Eagles","Cleveland Browns"],difficulty:3},
  {name:"Cam Newton",teams:["Carolina Panthers","New England Patriots","Carolina Panthers"],difficulty:2},
  {name:"Baker Mayfield",teams:["Cleveland Browns","Carolina Panthers","Los Angeles Rams","Tampa Bay Buccaneers"],difficulty:2},
  {name:"Robert Griffin III",teams:["Washington Redskins","Cleveland Browns","Baltimore Ravens"],difficulty:2},
  {name:"Jameis Winston",teams:["Tampa Bay Buccaneers","New Orleans Saints","Cleveland Browns"],difficulty:3},
  {name:"Marcus Mariota",teams:["Tennessee Titans","Las Vegas Raiders","Atlanta Falcons","Philadelphia Eagles","Washington Commanders"],difficulty:3},
  {name:"Jalen Ramsey",teams:["Jacksonville Jaguars","Los Angeles Rams","Miami Dolphins"],difficulty:2},
];
