// NFL Career Path data — curated notable retired players
// Teams listed in CHRONOLOGICAL order (career progression)
// Last updated: February 2026

export const NFL_CAREER_PATHS = [
  // ── Quarterbacks ──
  {name:"Tom Brady",teams:["New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Peyton Manning",teams:["Indianapolis Colts","Denver Broncos"]},
  {name:"Brett Favre",teams:["Atlanta Falcons","Green Bay Packers","New York Jets","Minnesota Vikings"]},
  {name:"Drew Brees",teams:["San Diego Chargers","New Orleans Saints"]},
  {name:"Joe Montana",teams:["San Francisco 49ers","Kansas City Chiefs"]},
  {name:"Steve Young",teams:["Tampa Bay Buccaneers","San Francisco 49ers"]},
  {name:"Warren Moon",teams:["Houston Oilers","Minnesota Vikings","Seattle Seahawks","Kansas City Chiefs"]},
  {name:"Matt Ryan",teams:["Atlanta Falcons","Indianapolis Colts"]},
  {name:"Philip Rivers",teams:["San Diego Chargers","Indianapolis Colts"]},
  {name:"Carson Palmer",teams:["Cincinnati Bengals","Oakland Raiders","Arizona Cardinals"]},
  {name:"Kurt Warner",teams:["St. Louis Rams","New York Giants","Arizona Cardinals"]},
  {name:"Donovan McNabb",teams:["Philadelphia Eagles","Washington Redskins","Minnesota Vikings"]},
  {name:"Michael Vick",teams:["Atlanta Falcons","Philadelphia Eagles","New York Jets","Pittsburgh Steelers"]},
  {name:"Cam Newton",teams:["Carolina Panthers","New England Patriots"]},
  {name:"Alex Smith",teams:["San Francisco 49ers","Kansas City Chiefs","Washington Commanders"]},
  {name:"Matthew Stafford",teams:["Detroit Lions","Los Angeles Rams"]},
  {name:"Jay Cutler",teams:["Denver Broncos","Chicago Bears","Miami Dolphins"]},
  {name:"Ryan Fitzpatrick",teams:["St. Louis Rams","Cincinnati Bengals","Buffalo Bills","Tennessee Titans","Houston Texans","New York Jets","Tampa Bay Buccaneers","Miami Dolphins","Washington Commanders"]},
  {name:"Drew Bledsoe",teams:["New England Patriots","Buffalo Bills","Dallas Cowboys"]},
  {name:"Randall Cunningham",teams:["Philadelphia Eagles","Minnesota Vikings","Dallas Cowboys","Baltimore Ravens"]},
  {name:"Steve McNair",teams:["Tennessee Titans","Baltimore Ravens"]},
  {name:"Chad Pennington",teams:["New York Jets","Miami Dolphins"]},
  {name:"Sam Bradford",teams:["St. Louis Rams","Philadelphia Eagles","Minnesota Vikings","Arizona Cardinals"]},
  {name:"Robert Griffin III",teams:["Washington Redskins","Cleveland Browns","Baltimore Ravens"]},

  // ── Running Backs ──
  {name:"Emmitt Smith",teams:["Dallas Cowboys","Arizona Cardinals"]},
  {name:"Eric Dickerson",teams:["Los Angeles Rams","Indianapolis Colts","Los Angeles Raiders","Atlanta Falcons"]},
  {name:"LaDainian Tomlinson",teams:["San Diego Chargers","New York Jets"]},
  {name:"Adrian Peterson",teams:["Minnesota Vikings","New Orleans Saints","Arizona Cardinals","Washington Redskins","Detroit Lions","Tennessee Titans","Seattle Seahawks"]},
  {name:"Frank Gore",teams:["San Francisco 49ers","Indianapolis Colts","Miami Dolphins","Buffalo Bills","New York Jets"]},
  {name:"Marshawn Lynch",teams:["Buffalo Bills","Seattle Seahawks","Oakland Raiders"]},
  {name:"DeMarco Murray",teams:["Dallas Cowboys","Philadelphia Eagles","Tennessee Titans"]},
  {name:"Todd Gurley",teams:["St. Louis Rams","Atlanta Falcons"]},
  {name:"Arian Foster",teams:["Houston Texans","Miami Dolphins"]},
  {name:"Chris Johnson",teams:["Tennessee Titans","New York Jets","Arizona Cardinals"]},
  {name:"Edgerrin James",teams:["Indianapolis Colts","Arizona Cardinals","Seattle Seahawks"]},
  {name:"Ricky Williams",teams:["New Orleans Saints","Miami Dolphins","Baltimore Ravens"]},
  {name:"Corey Dillon",teams:["Cincinnati Bengals","New England Patriots"]},
  {name:"Clinton Portis",teams:["Denver Broncos","Washington Redskins"]},
  {name:"Curtis Martin",teams:["New England Patriots","New York Jets"]},
  {name:"Jerome Bettis",teams:["Los Angeles Rams","Pittsburgh Steelers"]},
  {name:"Marshall Faulk",teams:["Indianapolis Colts","St. Louis Rams"]},
  {name:"Eddie George",teams:["Tennessee Titans","Dallas Cowboys"]},
  {name:"Thurman Thomas",teams:["Buffalo Bills","Miami Dolphins"]},
  {name:"Marcus Allen",teams:["Los Angeles Raiders","Kansas City Chiefs"]},
  {name:"Earl Campbell",teams:["Houston Oilers","New Orleans Saints"]},
  {name:"Tony Dorsett",teams:["Dallas Cowboys","Denver Broncos"]},
  {name:"O.J. Simpson",teams:["Buffalo Bills","San Francisco 49ers"]},
  {name:"Matt Forte",teams:["Chicago Bears","New York Jets"]},
  {name:"Reggie Bush",teams:["New Orleans Saints","Miami Dolphins","Detroit Lions","San Francisco 49ers","Buffalo Bills"]},

  // ── Wide Receivers ──
  {name:"Jerry Rice",teams:["San Francisco 49ers","Oakland Raiders","Seattle Seahawks"]},
  {name:"Randy Moss",teams:["Minnesota Vikings","Oakland Raiders","New England Patriots","Minnesota Vikings","Tennessee Titans","San Francisco 49ers"]},
  {name:"Terrell Owens",teams:["San Francisco 49ers","Philadelphia Eagles","Dallas Cowboys","Buffalo Bills","Cincinnati Bengals"]},
  {name:"Antonio Brown",teams:["Pittsburgh Steelers","Oakland Raiders","New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Julio Jones",teams:["Atlanta Falcons","Tennessee Titans","Tampa Bay Buccaneers"]},
  {name:"Dez Bryant",teams:["Dallas Cowboys","New Orleans Saints"]},
  {name:"Demaryius Thomas",teams:["Denver Broncos","Houston Texans","New England Patriots","New York Jets"]},
  {name:"Brandon Marshall",teams:["Denver Broncos","Miami Dolphins","Chicago Bears","New York Jets","New York Giants","Seattle Seahawks","New Orleans Saints"]},
  {name:"Wes Welker",teams:["San Diego Chargers","Miami Dolphins","New England Patriots","Denver Broncos"]},
  {name:"Steve Smith",teams:["Carolina Panthers","Baltimore Ravens"]},
  {name:"Andre Johnson",teams:["Houston Texans","Indianapolis Colts","Tennessee Titans"]},
  {name:"Anquan Boldin",teams:["Arizona Cardinals","Baltimore Ravens","San Francisco 49ers","Detroit Lions"]},
  {name:"Isaac Bruce",teams:["Los Angeles Rams","San Francisco 49ers"]},
  {name:"Cris Carter",teams:["Philadelphia Eagles","Minnesota Vikings","Miami Dolphins"]},
  {name:"Art Monk",teams:["Washington Redskins","New York Jets","Philadelphia Eagles"]},
  {name:"Chad Johnson",teams:["Cincinnati Bengals","New England Patriots","Miami Dolphins"]},
  {name:"DeSean Jackson",teams:["Philadelphia Eagles","Washington Redskins","Tampa Bay Buccaneers","Philadelphia Eagles","Los Angeles Rams","Las Vegas Raiders"]},
  {name:"Golden Tate",teams:["Seattle Seahawks","Detroit Lions","Philadelphia Eagles","New York Giants"]},
  {name:"Emmanuel Sanders",teams:["Pittsburgh Steelers","Denver Broncos","San Francisco 49ers","New Orleans Saints","Buffalo Bills"]},

  // ── Tight Ends ──
  {name:"Tony Gonzalez",teams:["Kansas City Chiefs","Atlanta Falcons"]},
  {name:"Rob Gronkowski",teams:["New England Patriots","Tampa Bay Buccaneers"]},
  {name:"Jason Witten",teams:["Dallas Cowboys","Las Vegas Raiders"]},
  {name:"Shannon Sharpe",teams:["Denver Broncos","Baltimore Ravens","Denver Broncos"]},
  {name:"Jimmy Graham",teams:["New Orleans Saints","Seattle Seahawks","Green Bay Packers","Chicago Bears"]},
  {name:"Greg Olsen",teams:["Chicago Bears","Carolina Panthers","Seattle Seahawks"]},
  {name:"Vernon Davis",teams:["San Francisco 49ers","Denver Broncos","Washington Redskins"]},
  {name:"Delanie Walker",teams:["San Francisco 49ers","Tennessee Titans"]},

  // ── Offensive Linemen ──
  {name:"Larry Allen",teams:["Dallas Cowboys","San Francisco 49ers"]},
  {name:"Orlando Pace",teams:["St. Louis Rams","Chicago Bears"]},
  {name:"Alan Faneca",teams:["Pittsburgh Steelers","New York Jets","Arizona Cardinals"]},
  {name:"Andrew Whitworth",teams:["Cincinnati Bengals","Los Angeles Rams"]},

  // ── Defensive Linemen / Edge ──
  {name:"Reggie White",teams:["Philadelphia Eagles","Green Bay Packers","Carolina Panthers"]},
  {name:"Bruce Smith",teams:["Buffalo Bills","Washington Redskins"]},
  {name:"J.J. Watt",teams:["Houston Texans","Arizona Cardinals"]},
  {name:"Julius Peppers",teams:["Carolina Panthers","Chicago Bears","Green Bay Packers","Carolina Panthers"]},
  {name:"Jason Taylor",teams:["Miami Dolphins","Washington Redskins","New York Jets","Miami Dolphins"]},
  {name:"Dwight Freeney",teams:["Indianapolis Colts","San Diego Chargers","Arizona Cardinals","Atlanta Falcons","Detroit Lions","Seattle Seahawks"]},
  {name:"John Randle",teams:["Minnesota Vikings","Seattle Seahawks"]},
  {name:"Warren Sapp",teams:["Tampa Bay Buccaneers","Oakland Raiders"]},
  {name:"Vince Wilfork",teams:["New England Patriots","Houston Texans"]},
  {name:"DeMarcus Ware",teams:["Dallas Cowboys","Denver Broncos"]},
  {name:"Jared Allen",teams:["Kansas City Chiefs","Minnesota Vikings","Chicago Bears","Carolina Panthers"]},
  {name:"Justin Tuck",teams:["New York Giants","Oakland Raiders"]},
  {name:"Chris Long",teams:["St. Louis Rams","New England Patriots","Philadelphia Eagles"]},

  // ── Linebackers ──
  {name:"Junior Seau",teams:["San Diego Chargers","Miami Dolphins","New England Patriots"]},
  {name:"Terrell Suggs",teams:["Baltimore Ravens","Arizona Cardinals","Kansas City Chiefs"]},
  {name:"James Harrison",teams:["Pittsburgh Steelers","Cincinnati Bengals","New England Patriots"]},
  {name:"Clay Matthews",teams:["Green Bay Packers","Los Angeles Rams"]},

  // ── Defensive Backs ──
  {name:"Deion Sanders",teams:["Atlanta Falcons","San Francisco 49ers","Dallas Cowboys","Washington Redskins","Baltimore Ravens"]},
  {name:"Rod Woodson",teams:["Pittsburgh Steelers","San Francisco 49ers","Baltimore Ravens","Oakland Raiders"]},
  {name:"Charles Woodson",teams:["Oakland Raiders","Green Bay Packers","Oakland Raiders"]},
  {name:"Ed Reed",teams:["Baltimore Ravens","Houston Texans","New York Jets"]},
  {name:"Champ Bailey",teams:["Washington Redskins","Denver Broncos","New Orleans Saints"]},
  {name:"Darrelle Revis",teams:["New York Jets","Tampa Bay Buccaneers","New England Patriots","New York Jets","Kansas City Chiefs"]},
  {name:"Richard Sherman",teams:["Seattle Seahawks","San Francisco 49ers","Tampa Bay Buccaneers"]},
  {name:"Ty Law",teams:["New England Patriots","New York Jets","Kansas City Chiefs","Denver Broncos"]},
  {name:"Brian Dawkins",teams:["Philadelphia Eagles","Denver Broncos"]},
  {name:"John Lynch",teams:["Tampa Bay Buccaneers","Denver Broncos"]},
  {name:"Asante Samuel",teams:["New England Patriots","Philadelphia Eagles","Atlanta Falcons"]},
  {name:"Aqib Talib",teams:["Tampa Bay Buccaneers","New England Patriots","Denver Broncos","Los Angeles Rams","Miami Dolphins"]},
  {name:"Eric Weddle",teams:["San Diego Chargers","Baltimore Ravens","Los Angeles Rams"]},
  {name:"Joe Haden",teams:["Cleveland Browns","Pittsburgh Steelers"]},

  // ── Specialists ──
  {name:"Adam Vinatieri",teams:["New England Patriots","Indianapolis Colts"]},
  {name:"Morten Andersen",teams:["New Orleans Saints","Atlanta Falcons","New York Giants","Kansas City Chiefs","Minnesota Vikings"]},
  {name:"Sebastian Janikowski",teams:["Oakland Raiders","Seattle Seahawks"]},
];
