import { useState, useEffect, useRef } from "react";

// ── 2026 NFL Draft Order (1st round, estimated) ─────────────────────────────────────────
const INITIAL_PICKS = [
  { pick: 1,  team: "Las Vegas Raiders",        abbr: "LV",  color: "#A5ACAF" },
  { pick: 2,  team: "New York Jets",             abbr: "NYJ", color: "#125740" },
  { pick: 3,  team: "Arizona Cardinals",         abbr: "ARI", color: "#97233F" },
  { pick: 4,  team: "Tennessee Titans",          abbr: "TEN", color: "#4B92DB" },
  { pick: 5,  team: "New York Giants",           abbr: "NYG", color: "#0B2265" },
  { pick: 6,  team: "Cleveland Browns",          abbr: "CLE", color: "#FF3C00" },
  { pick: 7,  team: "Washington Commanders",     abbr: "WSH", color: "#5A1414" },
  { pick: 8,  team: "New Orleans Saints",        abbr: "NO",  color: "#D3BC8D" },
  { pick: 9,  team: "Kansas City Chiefs",        abbr: "KC",  color: "#E31837" },
  { pick: 10, team: "Cincinnati Bengals",        abbr: "CIN", color: "#FB4F14" },
  { pick: 11, team: "Miami Dolphins",            abbr: "MIA", color: "#008E97" },
  { pick: 12, team: "Dallas Cowboys",            abbr: "DAL", color: "#002244" },
  { pick: 13, team: "Los Angeles Rams",          abbr: "LAR", color: "#003594" },
  { pick: 14, team: "Baltimore Ravens",          abbr: "BAL", color: "#241773" },
  { pick: 15, team: "Tampa Bay Buccaneers",      abbr: "TB",  color: "#D50A0A" },
  { pick: 16, team: "New York Jets",             abbr: "NYJ", color: "#125740" },
  { pick: 17, team: "Detroit Lions",             abbr: "DET", color: "#0076B6" },
  { pick: 18, team: "Minnesota Vikings",         abbr: "MIN", color: "#4F2683" },
  { pick: 19, team: "Carolina Panthers",         abbr: "CAR", color: "#0085CA" },
  { pick: 20, team: "Dallas Cowboys",            abbr: "DAL", color: "#002244" },
  { pick: 21, team: "Pittsburgh Steelers",       abbr: "PIT", color: "#FFB612" },
  { pick: 22, team: "Los Angeles Chargers",      abbr: "LAC", color: "#0080C6" },
  { pick: 23, team: "Philadelphia Eagles",       abbr: "PHI", color: "#004C54" },
  { pick: 24, team: "Cleveland Browns",          abbr: "CLE", color: "#FF3C00" },
  { pick: 25, team: "Chicago Bears",             abbr: "CHI", color: "#0B162A" },
  { pick: 26, team: "Buffalo Bills",             abbr: "BUF", color: "#00338D" },
  { pick: 27, team: "San Francisco 49ers",       abbr: "SF",  color: "#AA0000" },
  { pick: 28, team: "Houston Texans",            abbr: "HOU", color: "#03202F" },
  { pick: 29, team: "Los Angeles Rams",          abbr: "LAR", color: "#003594" },
  { pick: 30, team: "Denver Broncos",            abbr: "DEN", color: "#FB4F14" },
  { pick: 31, team: "New England Patriots",      abbr: "NE",  color: "#002244" },
  { pick: 32, team: "Seattle Seahawks",          abbr: "SEA", color: "#002244" },
];

// ── 2026 NFL Draft Prospects (last updated February 26, 2026) ──────────────────────
// Generated by refresh-prospects.cjs v2 — run again to update

const ALL_PROSPECTS = [
  {
    "name": "Fernando Mendoza",
    "position": "QB",
    "school": "California"
  },
  {
    "name": "Arvell Reese",
    "position": "LB",
    "school": "Ohio State"
  },
  {
    "name": "Rueben Bain Jr.",
    "position": "EDGE",
    "school": "Miami"
  },
  {
    "name": "Caleb Downs",
    "position": "S",
    "school": "Ohio State"
  },
  {
    "name": "Francis Mauigoa",
    "position": "OT",
    "school": "Miami"
  },
  {
    "name": "Jeremiyah Love",
    "position": "RB",
    "school": "Notre Dame"
  },
  {
    "name": "Carnell Tate",
    "position": "WR",
    "school": "Ohio State"
  },
  {
    "name": "Peter Woods",
    "position": "DT",
    "school": "Clemson"
  },
  {
    "name": "Kenyon Sadiq",
    "position": "TE",
    "school": "Oregon"
  },
  {
    "name": "Kayden McDonald",
    "position": "DT",
    "school": "Ohio State"
  },
  {
    "name": "David Bailey",
    "position": "EDGE",
    "school": "Stanford"
  },
  {
    "name": "Keldric Faulk",
    "position": "EDGE",
    "school": "LSU"
  },
  {
    "name": "K.C. Concepcion",
    "position": "WR",
    "school": "Texas A&M"
  },
  {
    "name": "Spencer Fano",
    "position": "OT",
    "school": "Utah"
  },
  {
    "name": "Ty Simpson",
    "position": "QB",
    "school": "Alabama"
  },
  {
    "name": "Sonny Styles",
    "position": "S",
    "school": "Ohio State"
  },
  {
    "name": "Mansoor Delane",
    "position": "CB",
    "school": "LSU"
  },
  {
    "name": "Jake Golday",
    "position": "LB",
    "school": "Cincinnati"
  },
  {
    "name": "Zion Young",
    "position": "EDGE",
    "school": "Missouri"
  },
  {
    "name": "Cashius Howell",
    "position": "EDGE",
    "school": "Texas A&M"
  },
  {
    "name": "Drew Allar",
    "position": "QB",
    "school": "Penn State"
  },
  {
    "name": "Harold Perkins Jr.",
    "position": "LB",
    "school": "LSU"
  },
  {
    "name": "Davion Igbinosun",
    "position": "CB",
    "school": "Ohio State"
  },
  {
    "name": "Jordyn Tyson",
    "position": "WR",
    "school": "Arizona State"
  },
  {
    "name": "Chase Bisontis",
    "position": "IOL",
    "school": "Texas A&M"
  },
  {
    "name": "Caleb Lomu",
    "position": "OT",
    "school": "Utah"
  },
  {
    "name": "Garrett Nussmeier",
    "position": "QB",
    "school": "LSU"
  },
  {
    "name": "D'Angelo Ponds",
    "position": "CB",
    "school": "Indiana"
  },
  {
    "name": "Akheem Mesidor",
    "position": "EDGE",
    "school": "Miami"
  },
  {
    "name": "Caleb Banks",
    "position": "DT",
    "school": "Florida"
  },
  {
    "name": "Eli Stowers",
    "position": "TE",
    "school": "Vanderbilt"
  },
  {
    "name": "Carson Beck",
    "position": "QB",
    "school": "Miami"
  },
  {
    "name": "Jermod McCoy",
    "position": "CB",
    "school": "Tennessee"
  },
  {
    "name": "T.J. Parker",
    "position": "EDGE",
    "school": "Clemson"
  },
  {
    "name": "Nicholas Singleton",
    "position": "RB",
    "school": "Penn State"
  },
  {
    "name": "Kaytron Allen",
    "position": "RB",
    "school": "Penn State"
  },
  {
    "name": "Max Klare",
    "position": "TE",
    "school": "Ohio State"
  },
  {
    "name": "Zachariah Branch",
    "position": "WR",
    "school": "Georgia"
  },
  {
    "name": "Brandon Cisse",
    "position": "CB",
    "school": "South Carolina"
  },
  {
    "name": "Jalen Lemon",
    "position": "WR",
    "school": "Purdue"
  },
  {
    "name": "Blake Miller",
    "position": "OT",
    "school": "Clemson"
  },
  {
    "name": "Malachi Fields",
    "position": "WR",
    "school": "Notre Dame"
  },
  {
    "name": "Avieon Terrell",
    "position": "CB",
    "school": "Clemson"
  },
  {
    "name": "Anthony Hill Jr.",
    "position": "LB",
    "school": "Texas"
  },
  {
    "name": "Jadarian Price",
    "position": "RB",
    "school": "Notre Dame"
  },
  {
    "name": "Chris Johnson",
    "position": "CB",
    "school": "San Diego State"
  },
  {
    "name": "Dani Dennis-Sutton",
    "position": "EDGE",
    "school": "Penn State"
  },
  {
    "name": "Monroe Freeling",
    "position": "OT",
    "school": "Georgia"
  },
  {
    "name": "Genesis Smith",
    "position": "S",
    "school": "Arizona"
  },
  {
    "name": "Brenen Thompson",
    "position": "WR",
    "school": "Mississippi State"
  },
  {
    "name": "Cole Payton",
    "position": "QB",
    "school": "North Dakota State"
  },
  {
    "name": "Malik Muhammad",
    "position": "CB",
    "school": "Texas"
  },
  {
    "name": "Lee Hunter",
    "position": "EDGE",
    "school": "Texas Tech"
  },
  {
    "name": "Romello Height",
    "position": "EDGE",
    "school": "Texas Tech"
  },
  {
    "name": "Joe Royer",
    "position": "TE",
    "school": "Cincinnati"
  },
  {
    "name": "Marvin Jones Jr.",
    "position": "EDGE",
    "school": "Florida State"
  },
  {
    "name": "Taurean York",
    "position": "LB",
    "school": "Texas A&M"
  },
  {
    "name": "Gabe Jacas",
    "position": "EDGE",
    "school": "Illinois"
  },
  {
    "name": "Emmanuel McNeil-Warren",
    "position": "S",
    "school": "Toledo"
  },
  {
    "name": "Olaivavega Ioane",
    "position": "IOL",
    "school": "Penn State"
  },
  {
    "name": "Chris McClellan",
    "position": "RB",
    "school": "Missouri"
  },
  {
    "name": "Will Lee III",
    "position": "CB",
    "school": "Texas A&M"
  },
  {
    "name": "Chandler Rivers",
    "position": "CB",
    "school": "Duke"
  },
  {
    "name": "Michael Trigg",
    "position": "TE",
    "school": "Baylor"
  },
  {
    "name": "Dallen Bentley",
    "position": "TE",
    "school": "Utah"
  },
  {
    "name": "J'Mari Taylor",
    "position": "RB",
    "school": "Virginia"
  },
  {
    "name": "Demond Claiborne",
    "position": "RB",
    "school": "Wake Forest"
  },
  {
    "name": "Jalon Kilgore",
    "position": "CB",
    "school": "South Carolina"
  },
  {
    "name": "Colton Hood",
    "position": "CB",
    "school": "Tennessee"
  },
  {
    "name": "Kyle Louis",
    "position": "LB",
    "school": "Pittsburgh"
  },
  {
    "name": "Caden Curry",
    "position": "EDGE",
    "school": "Ohio State"
  },
  {
    "name": "Treydan Stukes",
    "position": "CB",
    "school": "Arizona"
  },
  {
    "name": "CJ Allen",
    "position": "CB",
    "school": "Georgia"
  },
  {
    "name": "Aiden Fisher",
    "position": "LB",
    "school": "Indiana"
  },
  {
    "name": "Julian Neal",
    "position": "CB",
    "school": "Arkansas"
  },
  {
    "name": "Keionte Scott",
    "position": "S",
    "school": "Miami"
  },
  {
    "name": "Taylen Green",
    "position": "QB",
    "school": "Arkansas"
  },
  {
    "name": "Anthony Lucas",
    "position": "EDGE",
    "school": "USC"
  },
  {
    "name": "Nic Anderson",
    "position": "WR",
    "school": "Oklahoma"
  },
  {
    "name": "Jack Endries",
    "position": "TE",
    "school": "Texas"
  },
  {
    "name": "Marlin Klein",
    "position": "TE",
    "school": "Michigan"
  },
  {
    "name": "Max Iheanachor",
    "position": "OT",
    "school": "Arizona State"
  },
  {
    "name": "Jaishawn Barham",
    "position": "LB",
    "school": "South Carolina"
  },
  {
    "name": "Justin Joly",
    "position": "TE",
    "school": "NC State"
  },
  {
    "name": "Emmanuel Henderson Jr.",
    "position": "WR",
    "school": "Kansas"
  },
  {
    "name": "Ja'Kobi Lane",
    "position": "WR",
    "school": "South Carolina"
  },
  {
    "name": "Adam Randall",
    "position": "RB",
    "school": "Clemson"
  },
  {
    "name": "Isaiah World",
    "position": "OT",
    "school": "Georgia"
  },
  {
    "name": "Bryce Lance",
    "position": "WR",
    "school": "North Dakota State"
  },
  {
    "name": "Antonio Williams",
    "position": "WR",
    "school": "Clemson"
  },
  {
    "name": "Kaleb Proctor",
    "position": "WR",
    "school": "Southeastern Louisiana"
  },
  {
    "name": "Jalen Walthall",
    "position": "WR",
    "school": "Incarnate Word"
  },
  {
    "name": "Gennings Dunker",
    "position": "IOL",
    "school": "Iowa"
  },
  {
    "name": "Logan Jones",
    "position": "IOL",
    "school": "Iowa"
  },
  {
    "name": "CJ Daniels",
    "position": "WR",
    "school": "Miami"
  },
  {
    "name": "Kaden Wetjen",
    "position": "WR",
    "school": "Iowa"
  },
  {
    "name": "Xavier Nwankpa",
    "position": "S",
    "school": "Iowa"
  },
  {
    "name": "Malachi Lawrence",
    "position": "EDGE",
    "school": "UCF"
  },
  {
    "name": "Dae'Quan Wright",
    "position": "TE",
    "school": "Ole Miss"
  },
  {
    "name": "Rashul Faison",
    "position": "RB",
    "school": "Old Dominion"
  },
  {
    "name": "Boston Scott",
    "position": "WR",
    "school": "Washington"
  },
  {
    "name": "Emmanuel Pregnon",
    "position": "IOL",
    "school": "Oregon"
  },
  {
    "name": "A.J. Haulcy",
    "position": "CB",
    "school": "LSU"
  },
  {
    "name": "Barion Brown",
    "position": "WR",
    "school": "LSU"
  },
  {
    "name": "Ar'maj Reed-Adams",
    "position": "IOL",
    "school": "Texas A&M"
  },
  {
    "name": "Christen Miller",
    "position": "DT",
    "school": "Georgia"
  },
  {
    "name": "Kamari Ramsey",
    "position": "S",
    "school": "USC"
  },
  {
    "name": "Deontae Lawson",
    "position": "LB",
    "school": "Alabama"
  },
  {
    "name": "R Mason Thomas",
    "position": "EDGE",
    "school": "Oklahoma"
  },
  {
    "name": "Davison Igbinosun",
    "position": "CB",
    "school": "Ohio State"
  },
  {
    "name": "Chris Bell",
    "position": "WR",
    "school": "Louisville"
  },
  {
    "name": "Domonique Orange",
    "position": "DT",
    "school": "Iowa State"
  },
  {
    "name": "Derrick Moore",
    "position": "EDGE",
    "school": "Michigan"
  },
  {
    "name": "Chris Brazzell II",
    "position": "WR",
    "school": "Tennessee"
  },
  {
    "name": "Domani Jackson",
    "position": "CB",
    "school": "Alabama"
  },
  {
    "name": "Keith Abney II",
    "position": "CB",
    "school": "Arizona State"
  },
  {
    "name": "Cade Klubnik",
    "position": "QB",
    "school": "Clemson"
  },
  {
    "name": "Jack Pyburn",
    "position": "EDGE",
    "school": "LSU"
  },
  {
    "name": "Connor Lew",
    "position": "C",
    "school": "Auburn"
  },
  {
    "name": "Keylan Rutledge",
    "position": "OG",
    "school": "Georgia Tech"
  }
];

const PICK_SUGGESTIONS = {
  "1": [
    {
      "name": "Fernando Mendoza",
      "position": "QB",
      "school": "California"
    },
    {
      "name": "Arvell Reese",
      "position": "LB",
      "school": "Ohio State"
    },
    {
      "name": "Rueben Bain Jr.",
      "position": "EDGE",
      "school": "Miami"
    },
    {
      "name": "Caleb Downs",
      "position": "S",
      "school": "Ohio State"
    }
  ],
  "2": [
    {
      "name": "Rueben Bain Jr.",
      "position": "EDGE",
      "school": "Miami"
    },
    {
      "name": "Arvell Reese",
      "position": "LB",
      "school": "Ohio State"
    },
    {
      "name": "Caleb Downs",
      "position": "S",
      "school": "Ohio State"
    },
    {
      "name": "Francis Mauigoa",
      "position": "OT",
      "school": "Miami"
    }
  ],
  "3": [
    {
      "name": "Francis Mauigoa",
      "position": "OT",
      "school": "Miami"
    },
    {
      "name": "Jeremiyah Love",
      "position": "RB",
      "school": "Notre Dame"
    },
    {
      "name": "Carnell Tate",
      "position": "WR",
      "school": "Ohio State"
    },
    {
      "name": "Peter Woods",
      "position": "DT",
      "school": "Clemson"
    }
  ],
  "4": [
    {
      "name": "Carnell Tate",
      "position": "WR",
      "school": "Ohio State"
    },
    {
      "name": "Jeremiyah Love",
      "position": "RB",
      "school": "Notre Dame"
    },
    {
      "name": "Peter Woods",
      "position": "DT",
      "school": "Clemson"
    },
    {
      "name": "Kayden McDonald",
      "position": "DT",
      "school": "Ohio State"
    }
  ],
  "5": [
    {
      "name": "Peter Woods",
      "position": "DT",
      "school": "Clemson"
    },
    {
      "name": "Kayden McDonald",
      "position": "DT",
      "school": "Ohio State"
    },
    {
      "name": "David Bailey",
      "position": "EDGE",
      "school": "Stanford"
    },
    {
      "name": "Keldric Faulk",
      "position": "EDGE",
      "school": "LSU"
    }
  ],
  "6": [
    {
      "name": "David Bailey",
      "position": "EDGE",
      "school": "Stanford"
    },
    {
      "name": "Keldric Faulk",
      "position": "EDGE",
      "school": "LSU"
    },
    {
      "name": "K.C. Concepcion",
      "position": "WR",
      "school": "Texas A&M"
    },
    {
      "name": "Kenyon Sadiq",
      "position": "TE",
      "school": "Oregon"
    }
  ],
  "7": [
    {
      "name": "K.C. Concepcion",
      "position": "WR",
      "school": "Texas A&M"
    },
    {
      "name": "Spencer Fano",
      "position": "OT",
      "school": "Utah"
    },
    {
      "name": "Ty Simpson",
      "position": "QB",
      "school": "Alabama"
    },
    {
      "name": "Sonny Styles",
      "position": "S",
      "school": "Ohio State"
    }
  ],
  "8": [
    {
      "name": "Spencer Fano",
      "position": "OT",
      "school": "Utah"
    },
    {
      "name": "Ty Simpson",
      "position": "QB",
      "school": "Alabama"
    },
    {
      "name": "Mansoor Delane",
      "position": "CB",
      "school": "LSU"
    },
    {
      "name": "Jake Golday",
      "position": "LB",
      "school": "Cincinnati"
    }
  ],
  "9": [
    {
      "name": "Mansoor Delane",
      "position": "CB",
      "school": "LSU"
    },
    {
      "name": "Jake Golday",
      "position": "LB",
      "school": "Cincinnati"
    },
    {
      "name": "Zion Young",
      "position": "EDGE",
      "school": "Missouri"
    },
    {
      "name": "Cashius Howell",
      "position": "EDGE",
      "school": "Texas A&M"
    }
  ],
  "10": [
    {
      "name": "Zion Young",
      "position": "EDGE",
      "school": "Missouri"
    },
    {
      "name": "Cashius Howell",
      "position": "EDGE",
      "school": "Texas A&M"
    },
    {
      "name": "Drew Allar",
      "position": "QB",
      "school": "Penn State"
    },
    {
      "name": "Harold Perkins Jr.",
      "position": "LB",
      "school": "LSU"
    }
  ],
  "11": [
    {
      "name": "Drew Allar",
      "position": "QB",
      "school": "Penn State"
    },
    {
      "name": "Harold Perkins Jr.",
      "position": "LB",
      "school": "LSU"
    },
    {
      "name": "Davion Igbinosun",
      "position": "CB",
      "school": "Ohio State"
    },
    {
      "name": "Jordyn Tyson",
      "position": "WR",
      "school": "Arizona State"
    }
  ],
  "12": [
    {
      "name": "Jordyn Tyson",
      "position": "WR",
      "school": "Arizona State"
    },
    {
      "name": "Chase Bisontis",
      "position": "IOL",
      "school": "Texas A&M"
    },
    {
      "name": "Caleb Lomu",
      "position": "OT",
      "school": "Utah"
    },
    {
      "name": "Garrett Nussmeier",
      "position": "QB",
      "school": "LSU"
    }
  ],
  "13": [
    {
      "name": "Chase Bisontis",
      "position": "IOL",
      "school": "Texas A&M"
    },
    {
      "name": "Caleb Lomu",
      "position": "OT",
      "school": "Utah"
    },
    {
      "name": "D'Angelo Ponds",
      "position": "CB",
      "school": "Indiana"
    },
    {
      "name": "Akheem Mesidor",
      "position": "EDGE",
      "school": "Miami"
    }
  ],
  "14": [
    {
      "name": "D'Angelo Ponds",
      "position": "CB",
      "school": "Indiana"
    },
    {
      "name": "Akheem Mesidor",
      "position": "EDGE",
      "school": "Miami"
    },
    {
      "name": "Caleb Banks",
      "position": "DT",
      "school": "Florida"
    },
    {
      "name": "Eli Stowers",
      "position": "TE",
      "school": "Vanderbilt"
    }
  ],
  "15": [
    {
      "name": "Caleb Banks",
      "position": "DT",
      "school": "Florida"
    },
    {
      "name": "Carson Beck",
      "position": "QB",
      "school": "Miami"
    },
    {
      "name": "Jermod McCoy",
      "position": "CB",
      "school": "Tennessee"
    },
    {
      "name": "T.J. Parker",
      "position": "EDGE",
      "school": "Clemson"
    }
  ],
  "16": [
    {
      "name": "Carson Beck",
      "position": "QB",
      "school": "Miami"
    },
    {
      "name": "T.J. Parker",
      "position": "EDGE",
      "school": "Clemson"
    },
    {
      "name": "Nicholas Singleton",
      "position": "RB",
      "school": "Penn State"
    },
    {
      "name": "Kaytron Allen",
      "position": "RB",
      "school": "Penn State"
    }
  ],
  "17": [
    {
      "name": "Nicholas Singleton",
      "position": "RB",
      "school": "Penn State"
    },
    {
      "name": "Kaytron Allen",
      "position": "RB",
      "school": "Penn State"
    },
    {
      "name": "Max Klare",
      "position": "TE",
      "school": "Ohio State"
    },
    {
      "name": "Zachariah Branch",
      "position": "WR",
      "school": "Georgia"
    }
  ],
  "18": [
    {
      "name": "Zachariah Branch",
      "position": "WR",
      "school": "Georgia"
    },
    {
      "name": "Brandon Cisse",
      "position": "CB",
      "school": "South Carolina"
    },
    {
      "name": "Jalen Lemon",
      "position": "WR",
      "school": "Purdue"
    },
    {
      "name": "Blake Miller",
      "position": "OT",
      "school": "Clemson"
    }
  ],
  "19": [
    {
      "name": "Brandon Cisse",
      "position": "CB",
      "school": "South Carolina"
    },
    {
      "name": "Jalen Lemon",
      "position": "WR",
      "school": "Purdue"
    },
    {
      "name": "Blake Miller",
      "position": "OT",
      "school": "Clemson"
    },
    {
      "name": "Malachi Fields",
      "position": "WR",
      "school": "Notre Dame"
    }
  ],
  "20": [
    {
      "name": "Malachi Fields",
      "position": "WR",
      "school": "Notre Dame"
    },
    {
      "name": "Avieon Terrell",
      "position": "CB",
      "school": "Clemson"
    },
    {
      "name": "Anthony Hill Jr.",
      "position": "LB",
      "school": "Texas"
    },
    {
      "name": "Jadarian Price",
      "position": "RB",
      "school": "Notre Dame"
    }
  ],
  "21": [
    {
      "name": "Avieon Terrell",
      "position": "CB",
      "school": "Clemson"
    },
    {
      "name": "Anthony Hill Jr.",
      "position": "LB",
      "school": "Texas"
    },
    {
      "name": "Chris Johnson",
      "position": "CB",
      "school": "San Diego State"
    },
    {
      "name": "Dani Dennis-Sutton",
      "position": "EDGE",
      "school": "Penn State"
    }
  ],
  "22": [
    {
      "name": "Chris Johnson",
      "position": "CB",
      "school": "San Diego State"
    },
    {
      "name": "Dani Dennis-Sutton",
      "position": "EDGE",
      "school": "Penn State"
    },
    {
      "name": "Monroe Freeling",
      "position": "OT",
      "school": "Georgia"
    },
    {
      "name": "Genesis Smith",
      "position": "S",
      "school": "Arizona"
    }
  ],
  "23": [
    {
      "name": "Monroe Freeling",
      "position": "OT",
      "school": "Georgia"
    },
    {
      "name": "Genesis Smith",
      "position": "S",
      "school": "Arizona"
    },
    {
      "name": "Brenen Thompson",
      "position": "WR",
      "school": "Mississippi State"
    },
    {
      "name": "Cole Payton",
      "position": "QB",
      "school": "North Dakota State"
    }
  ],
  "24": [
    {
      "name": "Brenen Thompson",
      "position": "WR",
      "school": "Mississippi State"
    },
    {
      "name": "Malik Muhammad",
      "position": "CB",
      "school": "Texas"
    },
    {
      "name": "Lee Hunter",
      "position": "EDGE",
      "school": "Texas Tech"
    },
    {
      "name": "Romello Height",
      "position": "EDGE",
      "school": "Texas Tech"
    }
  ],
  "25": [
    {
      "name": "Malik Muhammad",
      "position": "CB",
      "school": "Texas"
    },
    {
      "name": "Lee Hunter",
      "position": "EDGE",
      "school": "Texas Tech"
    },
    {
      "name": "Joe Royer",
      "position": "TE",
      "school": "Cincinnati"
    },
    {
      "name": "Marvin Jones Jr.",
      "position": "EDGE",
      "school": "Florida State"
    }
  ],
  "26": [
    {
      "name": "Joe Royer",
      "position": "TE",
      "school": "Cincinnati"
    },
    {
      "name": "Marvin Jones Jr.",
      "position": "EDGE",
      "school": "Florida State"
    },
    {
      "name": "Taurean York",
      "position": "LB",
      "school": "Texas A&M"
    }
  ],
  "27": [
    {
      "name": "Taurean York",
      "position": "LB",
      "school": "Texas A&M"
    },
    {
      "name": "Gabe Jacas",
      "position": "EDGE",
      "school": "Illinois"
    },
    {
      "name": "Emmanuel McNeil-Warren",
      "position": "S",
      "school": "Toledo"
    }
  ],
  "28": [
    {
      "name": "Gabe Jacas",
      "position": "EDGE",
      "school": "Illinois"
    },
    {
      "name": "Emmanuel McNeil-Warren",
      "position": "S",
      "school": "Toledo"
    },
    {
      "name": "Olaivavega Ioane",
      "position": "IOL",
      "school": "Penn State"
    },
    {
      "name": "Chris McClellan",
      "position": "RB",
      "school": "Missouri"
    }
  ],
  "29": [
    {
      "name": "Olaivavega Ioane",
      "position": "IOL",
      "school": "Penn State"
    },
    {
      "name": "Chris McClellan",
      "position": "RB",
      "school": "Missouri"
    },
    {
      "name": "Will Lee III",
      "position": "CB",
      "school": "Texas A&M"
    },
    {
      "name": "Chandler Rivers",
      "position": "CB",
      "school": "Duke"
    }
  ],
  "30": [
    {
      "name": "Will Lee III",
      "position": "CB",
      "school": "Texas A&M"
    },
    {
      "name": "Chandler Rivers",
      "position": "CB",
      "school": "Duke"
    },
    {
      "name": "Michael Trigg",
      "position": "TE",
      "school": "Baylor"
    },
    {
      "name": "Dallen Bentley",
      "position": "TE",
      "school": "Utah"
    }
  ],
  "31": [
    {
      "name": "Michael Trigg",
      "position": "TE",
      "school": "Baylor"
    },
    {
      "name": "J'Mari Taylor",
      "position": "RB",
      "school": "Virginia"
    },
    {
      "name": "Demond Claiborne",
      "position": "RB",
      "school": "Wake Forest"
    },
    {
      "name": "Jalon Kilgore",
      "position": "CB",
      "school": "South Carolina"
    }
  ],
  "32": [
    {
      "name": "J'Mari Taylor",
      "position": "RB",
      "school": "Virginia"
    },
    {
      "name": "Jalon Kilgore",
      "position": "CB",
      "school": "South Carolina"
    },
    {
      "name": "Colton Hood",
      "position": "CB",
      "school": "Tennessee"
    },
    {
      "name": "Kyle Louis",
      "position": "LB",
      "school": "Pittsburgh"
    }
  ]
};



const ALL_TEAMS = [
  { team: "Arizona Cardinals",      abbr: "ARI", color: "#97233F" },
  { team: "Atlanta Falcons",        abbr: "ATL", color: "#A71930" },
  { team: "Baltimore Ravens",       abbr: "BAL", color: "#241773" },
  { team: "Buffalo Bills",          abbr: "BUF", color: "#00338D" },
  { team: "Carolina Panthers",      abbr: "CAR", color: "#0085CA" },
  { team: "Chicago Bears",          abbr: "CHI", color: "#0B162A" },
  { team: "Cincinnati Bengals",     abbr: "CIN", color: "#FB4F14" },
  { team: "Cleveland Browns",       abbr: "CLE", color: "#FF3C00" },
  { team: "Dallas Cowboys",         abbr: "DAL", color: "#002244" },
  { team: "Denver Broncos",         abbr: "DEN", color: "#FB4F14" },
  { team: "Detroit Lions",          abbr: "DET", color: "#0076B6" },
  { team: "Green Bay Packers",      abbr: "GB",  color: "#203731" },
  { team: "Houston Texans",         abbr: "HOU", color: "#03202F" },
  { team: "Indianapolis Colts",     abbr: "IND", color: "#002C5F" },
  { team: "Jacksonville Jaguars",   abbr: "JAX", color: "#006778" },
  { team: "Kansas City Chiefs",     abbr: "KC",  color: "#E31837" },
  { team: "Las Vegas Raiders",      abbr: "LV",  color: "#A5ACAF" },
  { team: "Los Angeles Chargers",   abbr: "LAC", color: "#0080C6" },
  { team: "Los Angeles Rams",       abbr: "LAR", color: "#003594" },
  { team: "Miami Dolphins",         abbr: "MIA", color: "#008E97" },
  { team: "Minnesota Vikings",      abbr: "MIN", color: "#4F2683" },
  { team: "New England Patriots",   abbr: "NE",  color: "#002244" },
  { team: "New Orleans Saints",     abbr: "NO",  color: "#D3BC8D" },
  { team: "New York Giants",        abbr: "NYG", color: "#0B2265" },
  { team: "New York Jets",          abbr: "NYJ", color: "#125740" },
  { team: "Philadelphia Eagles",    abbr: "PHI", color: "#004C54" },
  { team: "Pittsburgh Steelers",    abbr: "PIT", color: "#FFB612" },
  { team: "San Francisco 49ers",    abbr: "SF",  color: "#AA0000" },
  { team: "Seattle Seahawks",       abbr: "SEA", color: "#002244" },
  { team: "Tampa Bay Buccaneers",   abbr: "TB",  color: "#D50A0A" },
  { team: "Tennessee Titans",       abbr: "TEN", color: "#4B92DB" },
  { team: "Washington Commanders",  abbr: "WSH", color: "#5A1414" },
];

// ── Position group ordering and labels ────────────────────────────────────────
const POSITION_GROUPS = [
  { key: "QB",   label: "Quarterbacks" },
  { key: "RB",   label: "Running Backs" },
  { key: "WR",   label: "Wide Receivers" },
  { key: "TE",   label: "Tight Ends" },
  { key: "OT",   label: "Offensive Tackles" },
  { key: "IOL",  label: "Interior O-Line" },
  { key: "EDGE", label: "Edge Rushers" },
  { key: "DT",   label: "Defensive Tackles" },
  { key: "LB",   label: "Linebackers" },
  { key: "CB",   label: "Cornerbacks" },
  { key: "S",    label: "Safeties" },
];

// ── Styles ────────────────────────────────────────────────────────────────────
// ── Team Pantone colors (official primary) ───────────────────────────────────
const TEAM_COLOR = {
  "ARI": "#97233F",
  "ATL": "#A71930",
  "BAL": "#241773",
  "BUF": "#00338D",
  "CAR": "#0085CA",
  "CHI": "#0B162A",
  "CIN": "#FB4F14",
  "CLE": "#311D00",
  "DAL": "#002244",
  "DEN": "#002244",
  "DET": "#0076B6",
  "GB":  "#203731",
  "HOU": "#03202F",
  "IND": "#002C5F",
  "JAX": "#006778",
  "KC":  "#E31837",
  "LAC": "#0080C6",
  "LAR": "#003594",
  "LV":  "#A5ACAF",
  "MIA": "#008E97",
  "MIN": "#4F2683",
  "NE":  "#002244",
  "NO":  "#D3BC8D",
  "NYG": "#0B2265",
  "NYJ": "#125740",
  "PHI": "#004C54",
  "PIT": "#FFB612",
  "SEA": "#002244",
  "SF":  "#AA0000",
  "TB":  "#D50A0A",
  "TEN": "#4B92DB",
  "WSH": "#5A1414",
};

function getTeamColor(abbr) {
  return TEAM_COLOR[abbr] || "#444444";
}

// Tab text: use each team's non-white secondary color for contrast
const TAB_TEXT_COLOR = {
  "ARI": "#ffffff",
  "ATL": "#ffffff",
  "BAL": "#9E7C0C",
  "BUF": "#C60C30",
  "CAR": "#B0B7BC",
  "CHI": "#C83803",
  "CIN": "#000000",
  "CLE": "#FF3C00",
  "DAL": "#869397",
  "DEN": "#FB4F14",
  "DET": "#B0B7BC",
  "GB":  "#FFB612",
  "HOU": "#A71930",
  "IND": "#ffffff",
  "JAX": "#D7A22A",
  "KC":  "#FFB81C",
  "LAC": "#FFC20E",
  "LAR": "#FFC72C",
  "LV":  "#000000",
  "MIA": "#F58220",
  "MIN": "#FFC62F",
  "NE":  "#C60C30",
  "NO":  "#101820",
  "NYG": "#A71930",
  "NYJ": "#ffffff",
  "PHI": "#A5ACAF",
  "PIT": "#101820",
  "SEA": "#69BE28",
  "SF":  "#B3995D",
  "TB":  "#B1BABF",
  "TEN": "#ffffff",
  "WSH": "#FFB612",
};

function getTabTextColor(abbr) {
  return TAB_TEXT_COLOR[abbr] || "#ffffff";
}

const S = {
  app: {
    minHeight: "100vh",
    background: "#080810",
    fontFamily: "'Oswald', sans-serif",
    color: "#e8e0d0",
    padding: "56px 0 80px",
  },
  header: {
    background: "linear-gradient(180deg, #0d0d1a 0%, #080810 100%)",
    borderBottom: "1px solid #ffffff08",
    padding: "24px 28px 20px",
    textAlign: "center",
    position: "relative",
  },
  headerTitle: {
    fontSize: "clamp(22px, 4vw, 34px)",
    fontWeight: 700,
    fontStyle: "italic",
    fontFamily: "'Oswald', sans-serif",
    letterSpacing: 3,
    textTransform: "uppercase",
    background: "linear-gradient(135deg, #ffffff, #e0e0e8, #b0b0c0)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    margin: 0,
  },
  headerSub: {
    fontSize: 12,
    letterSpacing: 2,
    color: "#c8a050",
    marginTop: 4,
    textTransform: "uppercase",
  },
  grid: {
    maxWidth: 640,
    margin: "20px auto 0",
    padding: "0 16px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  pickCard: (isDragging) => ({
    background: "#0e0e1a",
    border: "1px solid #ffffff12",
    borderRadius: 10,
    cursor: "pointer",
    transition: "all 0.18s ease",
    opacity: isDragging ? 0.4 : 1,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "stretch",
  }),
  teamTab: (teamColor) => ({
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    background: `linear-gradient(120deg, ${teamColor} 0%, ${teamColor}cc 60%, ${teamColor}33 100%)`,
    minWidth: "22%",
    maxWidth: "22%",
    padding: "10px 0",
    flexShrink: 0,
    clipPath: "polygon(0 0, 100% 0, 82% 100%, 0 100%)",
  }),
  teamTabAbbr: (textColor) => ({
    fontSize: 15,
    fontWeight: 700,
    fontStyle: "italic",
    letterSpacing: 2,
    background: `linear-gradient(135deg, ${textColor}, ${textColor}aa)`,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    filter: "drop-shadow(1px 1px 2px rgba(0,0,0,0.5))",
    textTransform: "uppercase",
    marginRight: 8,
  }),
  pickNum: () => ({
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 2,
    color: "#ffffff66",
    textTransform: "uppercase",
    minWidth: 40,
    flexShrink: 0,
  }),
  playerName: () => ({
    fontSize: 22,
    fontWeight: 700,
    fontStyle: "italic",
    letterSpacing: 0.5,
    background: "linear-gradient(135deg, #ffffff, #e0e0e8, #b0b0c0)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    paddingRight: 6,
  }),
  playerPos: () => ({
    fontSize: 11,
    color: "#ffffff88",
    letterSpacing: 1,
    whiteSpace: "nowrap",
    flexShrink: 0,
  }),
  emptySlot: () => ({
    fontSize: 13,
    color: "#ffffff55",
    letterSpacing: 1,
    fontStyle: "italic",
  }),
  teamTag: (color) => ({
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 1.5,
    padding: "2px 8px",
    borderRadius: 4,
    background: color + "30",
    border: `1px solid ${color}66`,
    color: "#e8e0d0",
    textTransform: "uppercase",
    minWidth: 44,
    textAlign: "center",
    flexShrink: 0,
  }),
  tradeBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 1.5,
    padding: "2px 6px",
    borderRadius: 4,
    background: "#f0a03022",
    border: "1px solid #f0a03055",
    color: "#f0a030",
    textTransform: "uppercase",
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backdropFilter: "blur(4px)",
  },
  modalBox: {
    background: "#0e0e20",
    border: "1px solid #ffffff14",
    borderRadius: 16,
    padding: "28px 24px",
    maxWidth: 480,
    width: "100%",
    maxHeight: "85vh",
    overflowY: "auto",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  modalSub: {
    fontSize: 12,
    color: "#c8a050",
    letterSpacing: 1,
    marginBottom: 20,
    textTransform: "uppercase",
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 2.5,
    textTransform: "uppercase",
    color: "#c8a050",
    marginBottom: 8,
    marginTop: 16,
  },
  suggestionChip: (selected) => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "9px 12px",
    borderRadius: 8,
    border: `1px solid ${selected ? "#f0d07055" : "#ffffff10"}`,
    background: selected ? "#f0d07010" : "transparent",
    cursor: "pointer",
    transition: "all 0.15s",
    marginBottom: 6,
  }),
  btn: (variant) => ({
    padding: variant === "primary" ? "11px 24px" : "9px 18px",
    borderRadius: 8,
    border: variant === "primary" ? "none" : "1px solid #ffffff14",
    background: variant === "primary"
      ? "linear-gradient(135deg, #f0d070, #e87040)"
      : variant === "danger" ? "#e8403011" : "#ffffff08",
    color: variant === "primary" ? "#1a1008" : variant === "danger" ? "#e84030" : "#e8e0d0",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: "uppercase",
    cursor: "pointer",
    fontFamily: "'Oswald', sans-serif",
    transition: "all 0.15s",
    ...(variant === "danger" ? { border: "1px solid #e8403033" } : {}),
  }),
};

// ── Position group dropdown styles ────────────────────────────────────────────
const posGroupStyles = {
  header: (isOpen) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderRadius: 8,
    border: `1px solid ${isOpen ? "#ffffff18" : "#ffffff0a"}`,
    background: isOpen ? "#ffffff08" : "#ffffff04",
    cursor: "pointer",
    transition: "all 0.15s",
    marginBottom: isOpen ? 4 : 6,
  }),
  label: {
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "#e8e0d0",
  },
  count: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 1,
    color: "#ffffff77",
  },
  arrow: (isOpen) => ({
    fontSize: 10,
    color: "#ffffff77",
    transition: "transform 0.2s",
    transform: isOpen ? "rotate(180deg)" : "rotate(0deg)",
  }),
  list: {
    padding: "0 0 6px 0",
    marginBottom: 6,
  },
  playerRow: (selected, taken) => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderRadius: 8,
    border: `1px solid ${selected ? "#f0d07055" : "#ffffff08"}`,
    background: selected ? "#f0d07010" : "transparent",
    cursor: taken ? "default" : "pointer",
    opacity: taken ? 0.35 : 1,
    transition: "all 0.15s",
    marginBottom: 4,
  }),
  rank: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1,
    color: "#ffffff55",
    minWidth: 22,
    textAlign: "center",
    flexShrink: 0,
  },
  takenLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 1.5,
    color: "#e8403088",
    textTransform: "uppercase",
    flexShrink: 0,
  },
};

// ── Position Group Dropdown component ─────────────────────────────────────────
function PositionGroupDropdown({ group, prospects, selected, onSelect, draftedNames }) {
  const [isOpen, setIsOpen] = useState(false);

  const available = prospects.filter(p => !draftedNames.has(p.name));
  const taken = prospects.filter(p => draftedNames.has(p.name));

  return (
    <div>
      <div
        style={posGroupStyles.header(isOpen)}
        onClick={() => setIsOpen(!isOpen)}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={posGroupStyles.label}>{group.label}</span>
          <span style={posGroupStyles.count}>
            {available.length} available
          </span>
        </div>
        <span style={posGroupStyles.arrow(isOpen)}>▼</span>
      </div>

      {isOpen && (
        <div style={posGroupStyles.list}>
          {prospects.map((p, idx) => {
            const isTaken = draftedNames.has(p.name);
            const isSelected = selected?.name === p.name;
            return (
              <div
                key={p.name}
                style={posGroupStyles.playerRow(isSelected, isTaken)}
                onClick={() => !isTaken && onSelect(p)}
              >
                <span style={posGroupStyles.rank}>{idx + 1}</span>
                <div style={{ flex: 1, display: "flex", alignItems: "baseline", gap: 8 }}>
                  <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: 0.5 }}>
                    {p.name}
                  </div>
                  <div style={{ fontSize: 11, color: "#ffffff88", letterSpacing: 1, whiteSpace: "nowrap" }}>
                    {p.school}
                  </div>
                </div>
                {isTaken && <span style={posGroupStyles.takenLabel}>Drafted</span>}
                {isSelected && !isTaken && <span style={{ color: "#f0d070", fontSize: 14 }}>✓</span>}
              </div>
            );
          })}
          {prospects.length === 0 && (
            <div style={{ fontSize: 12, color: "#ffffff66", textAlign: "center", padding: "8px 0", fontStyle: "italic" }}>
              No prospects at this position
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Best Available Dropdown component ─────────────────────────────────────────
function BestAvailableDropdown({ allProspects, selected, onSelect, draftedNames }) {
  const [isOpen, setIsOpen] = useState(false);

  const available = allProspects.filter(p => !draftedNames.has(p.name));
  const totalCount = available.length;

  return (
    <div>
      <div
        style={{
          ...posGroupStyles.header(isOpen),
          border: `1px solid ${isOpen ? "#f0d07033" : "#f0d07018"}`,
          background: isOpen ? "#f0d07010" : "#f0d07008",
        }}
        onClick={() => setIsOpen(!isOpen)}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <span style={{ ...posGroupStyles.label, color: "#f0d070" }}>★ Best Available</span>
          <span style={posGroupStyles.count}>
            {totalCount} available
          </span>
        </div>
        <span style={posGroupStyles.arrow(isOpen)}>▼</span>
      </div>

      {isOpen && (
        <div style={posGroupStyles.list}>
          {available.map((p, idx) => {
            const isSelected = selected?.name === p.name;
            return (
              <div
                key={p.name}
                style={posGroupStyles.playerRow(isSelected, false)}
                onClick={() => onSelect(p)}
              >
                <span style={posGroupStyles.rank}>{idx + 1}</span>
                <div style={{ flex: 1, display: "flex", alignItems: "baseline", gap: 8 }}>
                  <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: 0.5 }}>
                    {p.name}
                  </div>
                  <div style={{ fontSize: 11, color: "#ffffff88", letterSpacing: 1, whiteSpace: "nowrap" }}>
                    {p.position} · {p.school}
                  </div>
                </div>
                {isSelected && <span style={{ color: "#f0d070", fontSize: 14 }}>✓</span>}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

// ── Player selection modal ────────────────────────────────────────────────────
function PickModal({ pick, suggestions, allProspects, draftedNames, onSelect, onTrade, onClear, onClose }) {
  const handlePick = (player) => onSelect(pick.pick, player);
  const [customOpen, setCustomOpen] = useState(false);
  const [customName, setCustomName] = useState("");
  const [customPos, setCustomPos] = useState("QB");
  const [customSchool, setCustomSchool] = useState("");

  // Build position groups from ALL_PROSPECTS (preserving rank order)
  const prospectsByPosition = {};
  for (const group of POSITION_GROUPS) {
    prospectsByPosition[group.key] = allProspects.filter(p => p.position === group.key);
  }

  const pickSuggestions = suggestions[pick.pick] || [];

  return (
    <div style={S.modal} onClick={e => e.target === e.currentTarget && onClose()}>
      <div style={S.modalBox}>
        {/* Header */}
        <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 16 }}>
          <div>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
              <span style={S.teamTag(getTeamColor(pick.abbr))}>{pick.abbr}</span>
              {pick.traded && <span style={{ ...S.tradeBadge, position: "static" }}>TRADED</span>}
            </div>
            <div style={S.modalTitle}>Pick #{pick.pick}</div>
            <div style={S.modalSub}>{pick.team}</div>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none", color: "#ffffff66", fontSize: 20, cursor: "pointer", padding: 0, lineHeight: 1 }}>✕</button>
        </div>

        {/* Actions */}
        {pick.player && (
          <div style={{ display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" }}>
            <button style={S.btn("danger")} onClick={() => onClear(pick.pick)}>
              Clear Pick
            </button>
          </div>
        )}

        {/* Current pick indicator */}
        {pick.player && (
          <div style={{
            padding: "10px 14px",
            borderRadius: 8,
            border: "1px solid #f0d07055",
            background: "#f0d07010",
            marginBottom: 16,
            display: "flex",
            alignItems: "baseline",
            gap: 8,
          }}>
            <span style={{ color: "#f0d070", fontSize: 14 }}>✓</span>
            <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: 0.5, color: "#f0d070" }}>{pick.player.name}</div>
            <div style={{ fontSize: 11, color: "#ffffff88", letterSpacing: 1 }}>{pick.player.position} · {pick.player.school}</div>
          </div>
        )}

        {/* Suggestions */}
        {pickSuggestions.length > 0 && (
          <>
            <div style={S.sectionLabel}>Suggestions for this pick</div>
            {pickSuggestions.map(p => {
              const isTaken = draftedNames.has(p.name);
              const isCurrent = pick.player?.name === p.name;
              return (
                <div
                  key={p.name}
                  style={{
                    ...S.suggestionChip(isCurrent),
                    opacity: isTaken ? 0.35 : 1,
                    cursor: isTaken ? "default" : "pointer",
                  }}
                  onClick={() => !isTaken && handlePick(p)}
                >
                  <div style={{ flex: 1, display: "flex", alignItems: "baseline", gap: 8 }}>
                    <div style={{ fontSize: 16, fontWeight: 700, letterSpacing: 0.5 }}>{p.name}</div>
                    <div style={{ fontSize: 11, color: "#ffffff88", letterSpacing: 1, whiteSpace: "nowrap" }}>{p.position} · {p.school}</div>
                  </div>
                  {isTaken && <span style={posGroupStyles.takenLabel}>Drafted</span>}
                  {isCurrent && !isTaken && <span style={{ color: "#f0d070", fontSize: 14 }}>✓</span>}
                </div>
              );
            })}
          </>
        )}

        {/* Big Board — Best Available + Position Group Dropdowns */}
        <div style={S.sectionLabel}>Big Board</div>
        <BestAvailableDropdown
          allProspects={allProspects}
          selected={pick.player}
          onSelect={handlePick}
          draftedNames={draftedNames}
        />
        {POSITION_GROUPS.map(group => (
          <PositionGroupDropdown
            key={group.key}
            group={group}
            prospects={prospectsByPosition[group.key]}
            selected={pick.player}
            onSelect={handlePick}
            draftedNames={draftedNames}
          />
        ))}

        {/* Custom Player Entry */}
        <div style={{ marginTop: 12 }}>
          <div
            style={{
              ...S.sectionLabel,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              userSelect: "none",
            }}
            onClick={() => setCustomOpen(!customOpen)}
          >
            <span>✏️ Add Custom Player</span>
            <span style={{ fontSize: 12, color: "#ffffff44" }}>{customOpen ? "▲" : "▼"}</span>
          </div>
          {customOpen && (
            <div style={{
              padding: 14,
              borderRadius: 8,
              background: "#ffffff08",
              border: "1px solid #ffffff10",
              display: "flex",
              flexDirection: "column",
              gap: 10,
            }}>
              <input
                type="text"
                placeholder="Player name"
                value={customName}
                onChange={e => setCustomName(e.target.value)}
                style={{
                  background: "#ffffff10",
                  border: "1px solid #ffffff20",
                  borderRadius: 6,
                  color: "#fff",
                  padding: "8px 12px",
                  fontSize: 14,
                  fontFamily: "'Oswald', sans-serif",
                  outline: "none",
                }}
              />
              <div style={{ display: "flex", gap: 8 }}>
                <select
                  value={customPos}
                  onChange={e => setCustomPos(e.target.value)}
                  style={{
                    background: "#ffffff10",
                    border: "1px solid #ffffff20",
                    borderRadius: 6,
                    color: "#fff",
                    padding: "8px 12px",
                    fontSize: 14,
                    fontFamily: "'Oswald', sans-serif",
                    outline: "none",
                    flex: "0 0 auto",
                  }}
                >
                  {["QB","RB","WR","TE","OT","OG","C","EDGE","DT","LB","CB","S","K","P"].map(p => (
                    <option key={p} value={p} style={{ background: "#1a1a2e" }}>{p}</option>
                  ))}
                </select>
                <input
                  type="text"
                  placeholder="School"
                  value={customSchool}
                  onChange={e => setCustomSchool(e.target.value)}
                  style={{
                    background: "#ffffff10",
                    border: "1px solid #ffffff20",
                    borderRadius: 6,
                    color: "#fff",
                    padding: "8px 12px",
                    fontSize: 14,
                    fontFamily: "'Oswald', sans-serif",
                    outline: "none",
                    flex: 1,
                  }}
                />
              </div>
              <button
                style={{
                  ...S.btn("primary"),
                  width: "100%",
                  opacity: customName.trim() && customSchool.trim() ? 1 : 0.4,
                  cursor: customName.trim() && customSchool.trim() ? "pointer" : "default",
                }}
                disabled={!customName.trim() || !customSchool.trim()}
                onClick={() => {
                  if (customName.trim() && customSchool.trim()) {
                    handlePick({ name: customName.trim(), position: customPos, school: customSchool.trim() });
                    setCustomName("");
                    setCustomSchool("");
                    setCustomOpen(false);
                  }
                }}
              >
                Add Player
              </button>
            </div>
          )}
        </div>

        {/* Trade option at bottom */}
        <div style={{ marginTop: 20, paddingTop: 16, borderTop: "1px solid #ffffff10" }}>
          <button style={{ ...S.btn("secondary"), color: "#f0a030", borderColor: "#f0a03033", background: "#f0a03011", width: "100%" }} onClick={() => onTrade(pick.pick)}>
            🔀 Trade Pick
          </button>
        </div>

      </div>
    </div>
  );
}

// ── Trade modal ───────────────────────────────────────────────────────────────
function TradeModal({ pick, picks, onConfirm, onClose }) {
  const [swapWith, setSwapWith] = useState(null);
  const [newTeam, setNewTeam] = useState(null);
  const [isSwap, setIsSwap] = useState(true);
  const [step, setStep] = useState("type"); // "type" | "team" | "swap_pick"

  return (
    <div style={S.modal} onClick={e => e.target === e.currentTarget && onClose()}>
      <div style={S.modalBox}>
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}>
          <div>
            <div style={S.modalTitle}>Trade Pick #{pick.pick}</div>
            <div style={S.modalSub}>{pick.team}</div>
          </div>
          <button onClick={onClose} style={{ background: "none", border: "none", color: "#ffffff66", fontSize: 20, cursor: "pointer", padding: 0 }}>✕</button>
        </div>

        {step === "type" && (
          <>
            <div style={S.sectionLabel}>What kind of trade?</div>
            {[
              { id: true,  label: "Pick swap", desc: "Two teams exchange picks. Details on additional compensation not required." },
              { id: false, label: "One-way acquisition", desc: "A team gets this pick and keeps their other pick(s). Details on additional compensation not required." },
            ].map(opt => (
              <div
                key={String(opt.id)}
                style={{ ...S.suggestionChip(isSwap === opt.id), marginBottom: 8 }}
                onClick={() => setIsSwap(opt.id)}
              >
                <div>
                  <div style={{ fontSize: 14, fontWeight: 700 }}>{opt.label}</div>
                  <div style={{ fontSize: 11, color: "#ffffff88" }}>{opt.desc}</div>
                </div>
                {isSwap === opt.id && <span style={{ color: "#f0d070" }}>✓</span>}
              </div>
            ))}
            <button style={{ ...S.btn("primary"), marginTop: 12 }} onClick={() => setStep("team")}>
              Next →
            </button>
          </>
        )}

        {step === "team" && (
          <>
            <div style={S.sectionLabel}>Which team is getting Pick #{pick.pick}?</div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6, maxHeight: 260, overflowY: "auto" }}>
              {ALL_TEAMS.filter(t => t.team !== pick.team).map(t => (
                <div
                  key={t.abbr}
                  style={{
                    padding: "6px 12px",
                    borderRadius: 6,
                    border: `1px solid ${newTeam?.abbr === t.abbr ? t.color + "88" : "#ffffff10"}`,
                    background: newTeam?.abbr === t.abbr ? t.color + "18" : "transparent",
                    cursor: "pointer",
                    fontSize: 12,
                    fontWeight: 700,
                    letterSpacing: 1.5,
                    color: newTeam?.abbr === t.abbr ? (t.color === "#A5ACAF" ? "#c8c8c8" : t.color) : "#ffffff66",
                    transition: "all 0.15s",
                  }}
                  onClick={() => setNewTeam(t)}
                >
                  {t.abbr}
                </div>
              ))}
            </div>
            {isSwap && newTeam && (
              <>
                <div style={{ ...S.sectionLabel, marginTop: 16 }}>Which pick does {newTeam.abbr} send back?</div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6, maxHeight: 160, overflowY: "auto" }}>
                  {picks.filter(p => p.team === newTeam.team && p.pick !== pick.pick).map(p => (
                    <div
                      key={p.pick}
                      style={{
                        padding: "6px 12px",
                        borderRadius: 6,
                        border: `1px solid ${swapWith?.pick === p.pick ? "#f0d07066" : "#ffffff10"}`,
                        background: swapWith?.pick === p.pick ? "#f0d07011" : "transparent",
                        cursor: "pointer",
                        fontSize: 12,
                        fontWeight: 700,
                        color: swapWith?.pick === p.pick ? "#f0d070" : "#ffffff55",
                        transition: "all 0.15s",
                      }}
                      onClick={() => setSwapWith(p)}
                    >
                      #{p.pick}
                    </div>
                  ))}
                  {picks.filter(p => p.team === newTeam.team && p.pick !== pick.pick).length === 0 && (
                    <div style={{ fontSize: 12, color: "#ffffff77", fontStyle: "italic" }}>
                      {newTeam.abbr} has no other 1st round picks
                    </div>
                  )}
                </div>
              </>
            )}
            <div style={{ display: "flex", gap: 8, marginTop: 16 }}>
              <button style={S.btn("secondary")} onClick={() => setStep("type")}>← Back</button>
              <button
                style={S.btn("primary")}
                disabled={!newTeam || (isSwap && !swapWith && picks.filter(p => p.team === newTeam?.team).length > 0)}
                onClick={() => onConfirm({ pickNum: pick.pick, newTeam, swapWith: isSwap ? swapWith : null })}
              >
                Confirm Trade
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// ── Share / image export ──────────────────────────────────────────────────────
function ShareModal({ picks, onClose }) {
  const canvasRef = useRef(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");

    document.fonts.ready.then(() => drawCanvas(canvas, ctx));

    function drawCanvas(canvas, ctx) {
      // 3:4 ratio — matches standard iPhone photo dimensions
      const W = 1080;
      const H = 1440;
      canvas.width = W;
      canvas.height = H;

      const COLS = 4;
      const ROWS = 8;
      const PAD = 28;
      const GAP = 10;
      const HEADER_H = 140;
      const FOOTER_H = 16;
      const GRID_W = W - PAD * 2;
      const GRID_H = H - HEADER_H - FOOTER_H;
      const CELL_W = Math.floor((GRID_W - (COLS - 1) * GAP) / COLS);
      const CELL_H = Math.floor((GRID_H - (ROWS - 1) * GAP) / ROWS);
      const RADIUS = 14;

      // Page background
      ctx.fillStyle = "#080810";
      ctx.fillRect(0, 0, W, H);

      // Subtle grid glow
      const bgGrad = ctx.createRadialGradient(W / 2, H / 2, 100, W / 2, H / 2, W);
      bgGrad.addColorStop(0, "#12121f");
      bgGrad.addColorStop(1, "#080810");
      ctx.fillStyle = bgGrad;
      ctx.fillRect(0, 0, W, H);

      // Title
      const titleGrad = ctx.createLinearGradient(W / 2 - 200, 20, W / 2 + 200, 65);
      titleGrad.addColorStop(0, "#ffffff");
      titleGrad.addColorStop(0.5, "#e0e0e8");
      titleGrad.addColorStop(1, "#b0b0c0");
      ctx.fillStyle = titleGrad;
      ctx.font = "italic bold 42px Oswald, sans-serif";
      ctx.textAlign = "center";
      ctx.fillText("2026 NFL DRAFT FIRST ROUND MOCK", W / 2, 60);

      // Site tag
      ctx.fillStyle = "#ffffffaa";
      ctx.font = "bold 22px Oswald, sans-serif";
      ctx.fillText("TrivialSports.com", W / 2, 92);

      // Divider
      ctx.strokeStyle = "#ffffff10";
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.moveTo(PAD, HEADER_H - 16);
      ctx.lineTo(W - PAD, HEADER_H - 16);
      ctx.stroke();

      // Draw grid of tiles
      picks.forEach((pick, i) => {
        const col = i % COLS;
        const row = Math.floor(i / COLS);
        const x = PAD + col * (CELL_W + GAP);
        const y = HEADER_H + row * (CELL_H + GAP);
        const teamColor = getTeamColor(pick.abbr);
        const textColor = TAB_TEXT_COLOR[pick.abbr] || "#ffffff";

        // Cell background with team color gradient
        const cellGrad = ctx.createLinearGradient(x, y, x, y + CELL_H);
        cellGrad.addColorStop(0, teamColor);
        cellGrad.addColorStop(1, teamColor + "aa");
        ctx.fillStyle = cellGrad;
        ctx.beginPath();
        ctx.roundRect(x, y, CELL_W, CELL_H, RADIUS);
        ctx.fill();

        // Subtle inner shadow / overlay for depth
        const overlay = ctx.createLinearGradient(x, y, x, y + CELL_H);
        overlay.addColorStop(0, "rgba(255,255,255,0.12)");
        overlay.addColorStop(0.5, "rgba(0,0,0,0)");
        overlay.addColorStop(1, "rgba(0,0,0,0.25)");
        ctx.fillStyle = overlay;
        ctx.beginPath();
        ctx.roundRect(x, y, CELL_W, CELL_H, RADIUS);
        ctx.fill();

        // Thin border
        ctx.strokeStyle = "rgba(255,255,255,0.08)";
        ctx.lineWidth = 1;
        ctx.beginPath();
        ctx.roundRect(x, y, CELL_W, CELL_H, RADIUS);
        ctx.stroke();

        const cx = x + CELL_W / 2;

        // Pick number — shaded triangle in top-left corner
        ctx.save();
        ctx.beginPath();
        ctx.roundRect(x, y, CELL_W, CELL_H, RADIUS);
        ctx.clip();
        const triSize = 76;
        ctx.fillStyle = "rgba(0,0,0,0.40)";
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.lineTo(x + triSize, y);
        ctx.lineTo(x, y + triSize);
        ctx.closePath();
        ctx.fill();
        ctx.restore();
        ctx.fillStyle = "#ffffffdd";
        ctx.font = "bold 26px Oswald, sans-serif";
        ctx.textAlign = "left";
        ctx.fillText(`${pick.pick}`, x + 10, y + 30);

        // Trade indicator — top-right
        if (pick.traded) {
          ctx.fillStyle = "rgba(0,0,0,0.35)";
          ctx.beginPath();
          ctx.roundRect(x + CELL_W - 56, y + 8, 48, 22, 6);
          ctx.fill();
          ctx.fillStyle = "#FFB612";
          ctx.font = "bold 11px Oswald, sans-serif";
          ctx.textAlign = "center";
          ctx.fillText("TRADE", x + CELL_W - 32, y + 24);
        }

        // Team abbreviation — upper right corner
        ctx.fillStyle = textColor;
        ctx.font = "bold 28px Oswald, sans-serif";
        ctx.textAlign = "right";
        ctx.fillText(pick.abbr, x + CELL_W - 10, y + 30);

        // Player info — centered in tile
        if (pick.player) {
          const nameParts = pick.player.name.split(" ");
          const firstName = nameParts[0];
          const lastName = nameParts.slice(1).join(" ");

          // First name — italic with diagonal gradient (smaller)
          ctx.shadowColor = "rgba(0,0,0,0.7)";
          ctx.shadowBlur = 6;
          ctx.shadowOffsetX = 1;
          ctx.shadowOffsetY = 1;
          const nameGrad1 = ctx.createLinearGradient(cx - 80, y + 30, cx + 80, y + 65);
          nameGrad1.addColorStop(0, "#ffffff");
          nameGrad1.addColorStop(0.5, "#e0e0e8");
          nameGrad1.addColorStop(1, "#b0b0c0");
          ctx.fillStyle = nameGrad1;
          ctx.font = "italic bold 26px Oswald, sans-serif";
          ctx.textAlign = "center";
          // Shrink first name if too wide
          let firstFont = 26;
          while (ctx.measureText(firstName).width > CELL_W - 16 && firstFont > 18) {
            firstFont -= 2;
            ctx.font = `italic bold ${firstFont}px Oswald, sans-serif`;
          }
          ctx.fillText(firstName, cx, y + 58);

          // Last name — italic with diagonal gradient (larger)
          const nameGrad2 = ctx.createLinearGradient(cx - 80, y + 65, cx + 80, y + 100);
          nameGrad2.addColorStop(0, "#ffffff");
          nameGrad2.addColorStop(0.5, "#e0e0e8");
          nameGrad2.addColorStop(1, "#b0b0c0");
          ctx.fillStyle = nameGrad2;
          ctx.font = "italic bold 40px Oswald, sans-serif";
          ctx.textAlign = "center";
          // Shrink last name if it's too wide
          let lastFont = 40;
          while (ctx.measureText(lastName).width > CELL_W - 16 && lastFont > 22) {
            lastFont -= 2;
            ctx.font = `italic bold ${lastFont}px Oswald, sans-serif`;
          }
          ctx.fillText(lastName, cx, y + 96);

          // Position + school
          ctx.shadowColor = "rgba(0,0,0,0.5)";
          ctx.shadowBlur = 4;
          ctx.shadowOffsetX = 1;
          ctx.shadowOffsetY = 1;
          ctx.fillStyle = "rgba(255,255,255,0.65)";
          ctx.font = "21px Oswald, sans-serif";
          ctx.textAlign = "center";
          const info = `${pick.player.position} · ${pick.player.school}`;
          const infoW = ctx.measureText(info).width;
          const displayInfo = infoW <= CELL_W - 16 ? info : pick.player.position;
          ctx.fillText(displayInfo, cx, y + 120);
          // Reset shadow
          ctx.shadowColor = "transparent";
          ctx.shadowBlur = 0;
          ctx.shadowOffsetX = 0;
          ctx.shadowOffsetY = 0;
        } else {
          ctx.fillStyle = "rgba(255,255,255,0.25)";
          ctx.font = "italic 24px Oswald, sans-serif";
          ctx.textAlign = "center";
          ctx.fillText("—", cx, y + 80);
        }
      });

      // (no footer)
    }
  }, [picks]);

  const saveImage = async () => {
    const dataUrl = canvasRef.current.toDataURL("image/png");

    if (navigator.share && navigator.canShare) {
      try {
        const blob = await (await fetch(dataUrl)).blob();
        const file = new File([blob], "2026-nfl-mock-draft.png", { type: "image/png" });
        if (navigator.canShare({ files: [file] })) {
          await navigator.share({
            files: [file],
            title: "2026 NFL Mock Draft",
            text: "Check out my 2026 NFL Mock Draft! trivialsports.com",
          });
          return;
        }
      } catch (err) {
        if (err.name !== "AbortError") console.error(err);
        return;
      }
    }

    const a = document.createElement("a");
    a.download = "2026-nfl-mock-draft.png";
    a.href = dataUrl;
    a.click();
  };

  return (
    <div style={S.modal} onClick={e => e.target === e.currentTarget && onClose()}>
      <div style={{ ...S.modalBox, maxWidth: 480 }}>
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}>
          <div style={S.modalTitle}>Share Your Mock Draft</div>
          <button onClick={onClose} style={{ background: "none", border: "none", color: "#ffffff66", fontSize: 20, cursor: "pointer", padding: 0 }}>✕</button>
        </div>
        <canvas ref={canvasRef} style={{ width: "100%", borderRadius: 8, border: "1px solid #ffffff10", display: "block", marginBottom: 16 }} />
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          <button style={S.btn("primary")} onClick={saveImage}>⬇ Save Image</button>
          <button style={S.btn("secondary")} onClick={onClose}>Close</button>
        </div>
      </div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────
export default function NFLMockDraft() {
  const [picks, setPicks] = useState(INITIAL_PICKS.map(p => ({ ...p, player: null, traded: false })));
  const [activePick, setActivePick] = useState(null);
  const [tradePick, setTradePick] = useState(null);
  const [showShare, setShowShare] = useState(false);
  const [dragSrc, setDragSrc] = useState(null);

  // Build a set of already-drafted player names (excluding current pick's player)
  const getDraftedNames = (excludePickNum) => {
    const names = new Set();
    for (const p of picks) {
      if (p.player && p.pick !== excludePickNum) {
        names.add(p.player.name);
      }
    }
    return names;
  };

  // ── Handlers ────────────────────────────────────────────────────────────────
  const handleSelect = (pickNum, player) => {
    setPicks(prev => prev.map(p => p.pick === pickNum ? { ...p, player } : p));
    setActivePick(null);
  };

  const handleClear = (pickNum) => {
    setPicks(prev => prev.map(p => p.pick === pickNum ? { ...p, player: null } : p));
    setActivePick(null);
  };

  const handleTrade = (pickNum) => {
    setActivePick(null);
    setTradePick(pickNum);
  };

  const handleTradeConfirm = ({ pickNum, newTeam, swapWith }) => {
    setPicks(prev => {
      const next = prev.map(p => {
        if (p.pick === pickNum) {
          return { ...p, team: newTeam.team, abbr: newTeam.abbr, color: newTeam.color, traded: true, player: p.player };
        }
        if (swapWith && p.pick === swapWith.pick) {
          const original = INITIAL_PICKS.find(ip => ip.pick === pickNum);
          return { ...p, team: original.team, abbr: original.abbr, color: original.color, traded: true };
        }
        return p;
      });
      return next;
    });
    setTradePick(null);
  };

  // ── Drag-and-drop to reorder filled picks ───────────────────────────────────
  const handleDragStart = (pickNum) => setDragSrc(pickNum);
  const handleDragOver = (e) => e.preventDefault();
  const handleDrop = (targetPickNum) => {
    if (dragSrc === null || dragSrc === targetPickNum) return;
    setPicks(prev => {
      const src = prev.find(p => p.pick === dragSrc);
      const tgt = prev.find(p => p.pick === targetPickNum);
      if (!src?.player || !tgt) return prev;
      return prev.map(p => {
        if (p.pick === dragSrc) return { ...p, player: tgt.player };
        if (p.pick === targetPickNum) return { ...p, player: src.player };
        return p;
      });
    });
    setDragSrc(null);
  };

  const filledCount = picks.filter(p => p.player).length;
  const activePkObj = activePick ? picks.find(p => p.pick === activePick) : null;
  const tradePkObj = tradePick ? picks.find(p => p.pick === tradePick) : null;

  return (
    <div style={S.app}>
      {/* Google Font */}
      <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;600;700&display=swap" rel="stylesheet" />

      {/* Header */}
      <div style={S.header}>
        <div style={S.headerTitle}>2026 NFL Draft</div>
        <div style={S.headerSub}>First Round Mock</div>

        <div style={{ marginTop: 6, fontSize: 11, color: "#c8a050", letterSpacing: 1 }}>
          {ALL_PROSPECTS.length} prospects · updated {new Date().toLocaleDateString("en-US", { month: "short", year: "numeric" })}
        </div>

        {/* Progress + share */}
        <div style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 16, marginTop: 14 }}>
          <div style={{ fontSize: 12, color: "#ffffff88", letterSpacing: 1 }}>
            <span style={{ color: "#f0d070", fontWeight: 700 }}>{filledCount}</span> / 32 picks made
          </div>
          {filledCount > 0 && (
            <button style={S.btn("primary")} onClick={() => setShowShare(true)}>
              Share Draft
            </button>
          )}
        </div>
      </div>

      {/* Pick grid */}
      <div style={S.grid}>
        {picks.map(pick => {
          const teamColor = getTeamColor(pick.abbr);
          const tabText = getTabTextColor(pick.abbr);
          return (
            <div
              key={pick.pick}
              style={S.pickCard(dragSrc === pick.pick)}
              onClick={() => setActivePick(pick.pick)}
              draggable={!!pick.player}
              onDragStart={() => handleDragStart(pick.pick)}
              onDragOver={handleDragOver}
              onDrop={() => handleDrop(pick.pick)}
            >
              <div style={S.teamTab(teamColor)}>
                <div style={S.teamTabAbbr(tabText)}>{pick.abbr}</div>
              </div>
              <div style={{ flex: 1, display: "flex", alignItems: "center", gap: 12, padding: "10px 14px" }}>
                <span style={S.pickNum()}>#{pick.pick}</span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  {pick.player ? (
                    <div style={{ display: "flex", alignItems: "baseline", gap: 8 }}>
                      <div style={S.playerName()}>{pick.player.name}</div>
                      <div style={S.playerPos()}>{pick.player.position} · {pick.player.school}</div>
                    </div>
                  ) : (
                    <div style={S.emptySlot()}>Select a player…</div>
                  )}
                </div>
                {pick.traded && <span style={S.tradeBadge}>Traded</span>}
              </div>
            </div>
          );
        })}
      </div>

      {/* Modals */}
      {activePkObj && (
        <PickModal
          pick={activePkObj}
          suggestions={PICK_SUGGESTIONS}
          allProspects={ALL_PROSPECTS}
          draftedNames={getDraftedNames(activePkObj.pick)}
          onSelect={handleSelect}
          onTrade={handleTrade}
          onClear={handleClear}
          onClose={() => setActivePick(null)}
        />
      )}
      {tradePkObj && (
        <TradeModal
          pick={tradePkObj}
          picks={picks}
          onConfirm={handleTradeConfirm}
          onClose={() => setTradePick(null)}
        />
      )}
      {showShare && (
        <ShareModal
          picks={picks}
          onClose={() => setShowShare(false)}
        />
      )}
    </div>
  );
}
